# Generated by Django 5.1.15 on 2026-09-04 05:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis_sessions', '0001_initial'),
        ('imagery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('detected_mode', models.CharField(choices=[('SINGLE_IMAGE', 'Single Image'), ('BI_TEMPORAL', 'Bi-Temporal'), ('CROSS_MODAL', 'Cross-Modal')], default='SINGLE_IMAGE', max_length=32)),
                ('detected_task', models.CharField(choices=[('VQA', 'Visual Question Answering'), ('CAPTION', 'Scene Captioning'), ('GROUNDING', 'Text-Guided Grounding'), ('CHANGE_DETECTION', 'Bi-Temporal Change Map'), ('CHANGE_VQA', 'Change-Based VQA'), ('OPTICAL_SAR_FUSION', 'Optical-SAR Fusion Analysis'), ('MISSION', 'Mission Mode (Multi-Step Intelligence Analysis)')], default='VQA', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('answer', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='imagery.imageasset')),
                ('image_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='imagery.imagepair')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='analysis_sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.IntegerField(default=1)),
                ('tool_name', models.CharField(max_length=128)),
                ('model_version', models.CharField(default='0.1-baseline', max_length=64)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=32)),
                ('output_ref', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_steps', to='queries.query')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
