# Generated by Django 5.1.15 on 2026-09-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='evidence_graph',
            field=models.JSONField(blank=True, default=dict, help_text='Multi-source evidence graph mapping'),
        ),
        migrations.AddField(
            model_name='query',
            name='follow_up_questions',
            field=models.JSONField(blank=True, default=list, help_text='Contextual follow-up suggestions'),
        ),
        migrations.AddField(
            model_name='query',
            name='structured_plan',
            field=models.JSONField(blank=True, default=dict, help_text='Validated QueryOptimizer JSON execution schema'),
        ),
    ]
