# Generated by Django 5.1.15 on 2026-09-06 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_sessions', '0004_alter_session_options_and_more'),
        ('imagery', '0003_imageryartifact_provenance_and_more'),
        ('queries', '0002_query_evidence_graph_query_follow_up_questions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='executionstep',
            name='agent_type',
            field=models.CharField(blank=True, default='', help_text='Specialist agent category, e.g. single_image, change_detection, gis, preprocessing.', max_length=128),
        ),
        migrations.AddField(
            model_name='executionstep',
            name='evidence_refs',
            field=models.JSONField(blank=True, default=list, help_text='References to evidence generated or validated by this step.'),
        ),
        migrations.AddField(
            model_name='executionstep',
            name='input_refs',
            field=models.JSONField(blank=True, default=list, help_text='References to input assets or upstream evidence consumed by this step.'),
        ),
        migrations.AddField(
            model_name='executionstep',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='query',
            name='answer_trace',
            field=models.JSONField(blank=True, default=list, help_text='Concise user-visible execution/evidence trace. This must never contain hidden chain-of-thought.'),
        ),
        migrations.AddField(
            model_name='query',
            name='clarification',
            field=models.JSONField(blank=True, default=dict, help_text='Structured clarification request when more context/data is required.'),
        ),
        migrations.AddField(
            model_name='query',
            name='clarification_required',
            field=models.BooleanField(default=False, help_text='True when the system cannot safely answer without additional user input or data.'),
        ),
        migrations.AddField(
            model_name='query',
            name='context_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Immutable-at-execution snapshot of map, location, imagery, viewport, AOI, conversation and other relevant context.'),
        ),
        migrations.AddField(
            model_name='query',
            name='evidence_bundle',
            field=models.JSONField(blank=True, default=dict, help_text='Final validated evidence bundle used by the answer composer.'),
        ),
        migrations.AddField(
            model_name='query',
            name='input_assets',
            field=models.ManyToManyField(blank=True, help_text='All imagery assets explicitly used as inputs for this query.', related_name='queries_many', to='imagery.imageasset'),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='model_version',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AlterField(
            model_name='query',
            name='confidence',
            field=models.FloatField(blank=True, help_text='Evidence-grounded confidence. This must not be interpreted as an unsupported probability of truth.', null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='evidence_graph',
            field=models.JSONField(blank=True, default=dict, help_text='Structured evidence graph produced by specialist agents. Contains observations, measurements, provenance and validation state.'),
        ),
        migrations.AlterField(
            model_name='query',
            name='follow_up_questions',
            field=models.JSONField(blank=True, default=list, help_text='Contextual follow-up questions generated when useful.'),
        ),
        migrations.AlterField(
            model_name='query',
            name='structured_plan',
            field=models.JSONField(blank=True, default=dict, help_text='Validated execution plan produced by the query planner.'),
        ),
        migrations.AddIndex(
            model_name='executionstep',
            index=models.Index(fields=['query', 'step_number'], name='exec_query_step_idx'),
        ),
        migrations.AddIndex(
            model_name='executionstep',
            index=models.Index(fields=['query', 'status'], name='exec_query_status_idx'),
        ),
        migrations.AddIndex(
            model_name='executionstep',
            index=models.Index(fields=['tool_name', 'status'], name='exec_tool_status_idx'),
        ),
        migrations.AddIndex(
            model_name='query',
            index=models.Index(fields=['session', '-created_at'], name='query_session_created_idx'),
        ),
        migrations.AddIndex(
            model_name='query',
            index=models.Index(fields=['user', '-created_at'], name='query_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='query',
            index=models.Index(fields=['status', '-created_at'], name='query_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='query',
            index=models.Index(fields=['detected_task', '-created_at'], name='query_task_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='executionstep',
            constraint=models.UniqueConstraint(fields=('query', 'step_number'), name='unique_query_execution_step'),
        ),
    ]
