# Generated by Django 5.1.15 on 2026-09-04 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_user_organization_project'),
        ('analysis_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='conversation_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.project'),
        ),
    ]
