# Generated by Django 5.1.15 on 2026-09-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_sessions', '0002_session_conversation_history_session_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='conversation_context',
            field=models.JSONField(blank=True, default=dict, help_text='Multi-turn conversational Earth analyst context state'),
        ),
    ]
