# Generated by Django 5.1.15 on 2026-09-06 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('analysis_sessions', '0003_session_conversation_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='session',
            name='conversation_context',
            field=models.JSONField(blank=True, default=dict, help_text='Durable Earth-analysis context including active imagery, map pin, AOI, selected pair, and recent query state.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='conversation_history',
            field=models.JSONField(blank=True, default=list, help_text='Durable conversation messages/events for this analysis session.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=32),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'status'], name='session_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['project', 'status'], name='session_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['updated_at'], name='session_updated_idx'),
        ),
    ]
