# Generated by Django 5.1.15 on 2026-09-04 05:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis_sessions', '0001_initial'),
        ('imagery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aoi_geometry', models.JSONField()),
                ('sensor', models.CharField(choices=[('SENTINEL-1', 'Sentinel-1 (SAR)'), ('SENTINEL-2', 'Sentinel-2 (Optical L2A)'), ('BOTH', 'Both (Optical + SAR)')], default='SENTINEL-2', max_length=32)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('max_cloud_cover', models.FloatField(blank=True, default=20.0, null=True)),
                ('status', models.CharField(choices=[('SEARCHING', 'Searching'), ('RESULTS_READY', 'Results Ready'), ('RETRIEVING', 'Retrieving'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='SEARCHING', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_requests', to='analysis_sessions.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcquisitionCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stac_item_id', models.CharField(max_length=255)),
                ('collection', models.CharField(max_length=128)),
                ('acquisition_date', models.DateField()),
                ('cloud_cover_pct', models.FloatField(blank=True, null=True)),
                ('footprint_geom', models.JSONField()),
                ('selected', models.BooleanField(default=False)),
                ('retrieved_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_candidate', to='imagery.imageasset')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='satellite.acquisitionrequest')),
            ],
            options={
                'ordering': ['cloud_cover_pct', '-acquisition_date'],
            },
        ),
    ]
