# Generated by Django 5.1.15 on 2026-09-04 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_sessions', '0002_session_conversation_history_session_project'),
        ('imagery', '0001_initial'),
        ('satellite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_url', models.URLField(max_length=512)),
                ('stac_endpoint', models.URLField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='copernicus', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('scenes_discovered', models.IntegerField(default=0)),
                ('scenes_ingested', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('geometry', models.JSONField(help_text='GeoJSON Polygon/MultiPolygon coordinates')),
                ('bbox', models.JSONField(help_text='[min_lon, min_lat, max_lon, max_lat]')),
                ('centroid', models.JSONField(blank=True, help_text='[lon, lat]', null=True)),
                ('area_sqkm', models.FloatField(default=0.0)),
                ('crs', models.CharField(default='EPSG:4326', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aois', to='analysis_sessions.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AOIMonitoring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cadence', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=16)),
                ('alert_on_change_pct', models.FloatField(default=5.0)),
                ('target_sensor', models.CharField(default='SENTINEL-2', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_schedules', to='satellite.areaofinterest')),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='copernicus', max_length=64)),
                ('collection', models.CharField(default='sentinel-2-l2a', max_length=128)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('platform', models.CharField(default='Sentinel-2A', max_length=64)),
                ('mission', models.CharField(default='Sentinel-2', max_length=64)),
                ('instrument', models.CharField(default='MSI', max_length=64)),
                ('acquisition_datetime', models.DateTimeField(db_index=True)),
                ('processing_level', models.CharField(default='LEVEL2A', max_length=64)),
                ('cloud_cover', models.FloatField(blank=True, null=True)),
                ('geometry', models.JSONField(help_text='GeoJSON footprint')),
                ('bbox', models.JSONField(help_text='[minx, miny, maxx, maxy]')),
                ('crs', models.CharField(default='EPSG:4326', max_length=32)),
                ('resolution', models.FloatField(default=10.0)),
                ('sensor', models.CharField(choices=[('OPTICAL', 'Optical'), ('SAR', 'Synthetic Aperture Radar')], default='OPTICAL', max_length=32)),
                ('modality', models.CharField(default='MULTISPECTRAL', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('stac_item_url', models.URLField(blank=True, max_length=512)),
                ('thumbnail_url', models.URLField(blank=True, max_length=512)),
                ('availability_status', models.CharField(choices=[('CATALOGUED', 'Catalogued in Remote STAC'), ('INDEXED', 'Metadata Locally Indexed'), ('CACHED', 'Assets Cached Locally / MinIO'), ('ARCHIVED', 'Archived in Cold Storage')], default='CATALOGUED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-acquisition_datetime'],
                'unique_together': {('provider', 'collection', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('URBAN_EXPANSION', 'Urban Expansion'), ('VEGETATION_LOSS', 'Vegetation Loss'), ('VEGETATION_GAIN', 'Vegetation Gain'), ('WATER_EXPANSION', 'Water Expansion'), ('WATER_REDUCTION', 'Water Reduction'), ('CONSTRUCTION', 'Construction'), ('ROAD_DEVELOPMENT', 'Road Development'), ('LAND_CLEARING', 'Land Clearing'), ('BURN_SCAR', 'Burn Scar'), ('UNKNOWN', 'Unknown / Anomaly')], default='URBAN_EXPANSION', max_length=64)),
                ('change_polygon', models.JSONField(help_text='GeoJSON Feature/Geometry of the detected change boundary')),
                ('area_hectares', models.FloatField(default=0.0)),
                ('change_percentage', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.85)),
                ('algorithm', models.CharField(default='NDVI_DIFFERENCING+CANNY_CONTOURS', max_length=128)),
                ('evidence_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='satellite.areaofinterest')),
                ('scene_after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_as_after', to='satellite.satellitescene')),
                ('scene_before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_as_before', to='satellite.satellitescene')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SatelliteCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('sensor_type', models.CharField(choices=[('OPTICAL', 'Multispectral / Optical'), ('SAR', 'Synthetic Aperture Radar (SAR)'), ('HYPERSPECTRAL', 'Hyperspectral'), ('THERMAL', 'Thermal Infrared')], default='OPTICAL', max_length=32)),
                ('platform', models.CharField(default='Sentinel-2', max_length=64)),
                ('instrument', models.CharField(default='MSI', max_length=64)),
                ('spatial_resolution_meters', models.FloatField(default=10.0)),
                ('temporal_revisit_days', models.FloatField(default=5.0)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='satellite.dataprovider')),
            ],
            options={
                'unique_together': {('provider', 'collection_id')},
            },
        ),
        migrations.CreateModel(
            name='SatelliteAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_key', models.CharField(help_text='e.g. B02, B03, B04, B08, visual, VV, VH', max_length=64)),
                ('asset_type', models.CharField(default='image/tiff; application=geotiff; profile=cloud-optimized', max_length=128)),
                ('href', models.TextField()),
                ('local_path', models.CharField(blank=True, max_length=512)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('byte_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='satellite.satellitescene')),
            ],
            options={
                'unique_together': {('scene', 'asset_key')},
            },
        ),
        migrations.CreateModel(
            name='DerivedRaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index_type', models.CharField(choices=[('NDVI', 'Normalized Difference Vegetation Index'), ('NDWI', 'Normalized Difference Water Index'), ('NDBI', 'Normalized Difference Built-up Index'), ('NBR', 'Normalized Burn Ratio'), ('FALSE_COLOR', 'False Color (NIR-Red-Green)'), ('SAR_RGB', 'SAR Dual-Pol (VV/VH/Ratio)')], default='NDVI', max_length=32)),
                ('thumbnail_url', models.TextField(blank=True)),
                ('min_val', models.FloatField(default=-1.0)),
                ('max_val', models.FloatField(default=1.0)),
                ('mean_val', models.FloatField(default=0.0)),
                ('std_val', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raster_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_derived_raster', to='imagery.imageasset')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_rasters', to='satellite.satellitescene')),
            ],
            options={
                'unique_together': {('scene', 'index_type')},
            },
        ),
        migrations.CreateModel(
            name='TemporalObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_date', models.DateField(db_index=True)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField()),
                ('cloud_cover', models.FloatField(blank=True, null=True)),
                ('quality_score', models.FloatField(default=1.0)),
                ('thumbnail_url', models.TextField(blank=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='satellite.areaofinterest')),
                ('derived_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporal_source', to='imagery.imageasset')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporal_observations', to='satellite.satellitescene')),
            ],
            options={
                'ordering': ['observation_date'],
                'unique_together': {('aoi', 'scene')},
            },
        ),
    ]
