# Generated by Django 5.1.15 on 2026-09-06 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_sessions', '0004_alter_session_options_and_more'),
        ('imagery', '0003_imageryartifact_provenance_and_more'),
        ('satellite', '0002_dataprovider_datasyncjob_areaofinterest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquisitioncandidate',
            options={'ordering': [models.OrderBy(models.F('cloud_cover_pct'), nulls_last=True), '-acquisition_date']},
        ),
        migrations.AlterModelOptions(
            name='aoimonitoring',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dataprovider',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='derivedraster',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='satellitecollection',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='derivedraster',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='satelliteasset',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='satellitecollection',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='satellitescene',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='temporalobservation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='acquisitioncandidate',
            name='assets_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Remote STAC asset metadata returned during discovery.'),
        ),
        migrations.AddField(
            model_name='acquisitioncandidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisitioncandidate',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='acquisitioncandidate',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='acquisitionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aoimonitoring',
            name='last_observation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aoimonitoring',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aoimonitoring',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='areaofinterest',
            name='properties',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='changeevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='datasyncjob',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='datasyncjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='derivedraster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='satelliteasset',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='satelliteasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='satellitecollection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satellitecollection',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='satellitecollection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='temporalobservation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='temporalobservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='acquisitioncandidate',
            name='acquisition_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='acquisitioncandidate',
            name='footprint_geom',
            field=models.JSONField(blank=True, help_text='Footprint returned by the remote catalogue.', null=True),
        ),
        migrations.AlterField(
            model_name='acquisitioncandidate',
            name='stac_item_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='acquisitionrequest',
            name='aoi_geometry',
            field=models.JSONField(help_text='GeoJSON geometry supplied by the user or map context.'),
        ),
        migrations.AlterField(
            model_name='acquisitionrequest',
            name='max_cloud_cover',
            field=models.FloatField(blank=True, help_text='Maximum requested cloud cover percentage, if specified.', null=True),
        ),
        migrations.AlterField(
            model_name='acquisitionrequest',
            name='sensor',
            field=models.CharField(choices=[('SENTINEL-1', 'Sentinel-1 (SAR)'), ('SENTINEL-2', 'Sentinel-2 (Optical)'), ('BOTH', 'Optical + SAR')], default='SENTINEL-2', max_length=32),
        ),
        migrations.AlterField(
            model_name='aoimonitoring',
            name='alert_on_change_pct',
            field=models.FloatField(blank=True, help_text='Optional user-defined alert threshold.', null=True),
        ),
        migrations.AlterField(
            model_name='aoimonitoring',
            name='target_sensor',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='areaofinterest',
            name='area_sqkm',
            field=models.FloatField(blank=True, help_text='Area only when calculated from valid geospatial data.', null=True),
        ),
        migrations.AlterField(
            model_name='areaofinterest',
            name='bbox',
            field=models.JSONField(blank=True, help_text='[min_x, min_y, max_x, max_y].', null=True),
        ),
        migrations.AlterField(
            model_name='areaofinterest',
            name='centroid',
            field=models.JSONField(blank=True, help_text='[x, y] derived from the supplied geometry.', null=True),
        ),
        migrations.AlterField(
            model_name='areaofinterest',
            name='crs',
            field=models.CharField(default='EPSG:4326', max_length=64),
        ),
        migrations.AlterField(
            model_name='areaofinterest',
            name='geometry',
            field=models.JSONField(help_text='GeoJSON Polygon/MultiPolygon geometry.'),
        ),
        migrations.AlterField(
            model_name='changeevent',
            name='algorithm',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='changeevent',
            name='area_hectares',
            field=models.FloatField(blank=True, help_text='Physical area only when valid geospatial measurement exists.', null=True),
        ),
        migrations.AlterField(
            model_name='changeevent',
            name='change_percentage',
            field=models.FloatField(blank=True, help_text='Percentage only when denominator and measurement are known.', null=True),
        ),
        migrations.AlterField(
            model_name='changeevent',
            name='change_polygon',
            field=models.JSONField(blank=True, help_text='Evidence-derived GeoJSON feature or geometry.', null=True),
        ),
        migrations.AlterField(
            model_name='changeevent',
            name='change_type',
            field=models.CharField(choices=[('URBAN_EXPANSION', 'Urban Expansion'), ('VEGETATION_LOSS', 'Vegetation Loss'), ('VEGETATION_GAIN', 'Vegetation Gain'), ('WATER_EXPANSION', 'Water Expansion'), ('WATER_REDUCTION', 'Water Reduction'), ('CONSTRUCTION', 'Construction'), ('ROAD_DEVELOPMENT', 'Road Development'), ('LAND_CLEARING', 'Land Clearing'), ('BURN_SCAR', 'Burn Scar'), ('UNKNOWN', 'Unknown / Anomaly')], default='UNKNOWN', max_length=64),
        ),
        migrations.AlterField(
            model_name='changeevent',
            name='confidence',
            field=models.FloatField(blank=True, help_text='Model/evidence confidence when explicitly produced.', null=True),
        ),
        migrations.AlterField(
            model_name='datasyncjob',
            name='provider',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='datasyncjob',
            name='scenes_discovered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datasyncjob',
            name='scenes_ingested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='derivedraster',
            name='index_type',
            field=models.CharField(choices=[('NDVI', 'Normalized Difference Vegetation Index'), ('NDWI', 'Normalized Difference Water Index'), ('NDBI', 'Normalized Difference Built-up Index'), ('NBR', 'Normalized Burn Ratio'), ('FALSE_COLOR', 'False Color'), ('SAR_RGB', 'SAR Dual-Polarization Visualization'), ('CHANGE_MASK', 'Change Mask'), ('CUSTOM', 'Custom Derived Raster')], max_length=32),
        ),
        migrations.AlterField(
            model_name='derivedraster',
            name='max_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='derivedraster',
            name='mean_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='derivedraster',
            name='min_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='derivedraster',
            name='std_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='satelliteasset',
            name='asset_key',
            field=models.CharField(help_text='STAC asset key such as B02, B03, B04, B08, VV, VH, visual.', max_length=128),
        ),
        migrations.AlterField(
            model_name='satelliteasset',
            name='asset_type',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='satelliteasset',
            name='href',
            field=models.TextField(help_text='Remote or source asset URL/path.'),
        ),
        migrations.AlterField(
            model_name='satelliteasset',
            name='local_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='satellitecollection',
            name='instrument',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='satellitecollection',
            name='platform',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='satellitecollection',
            name='sensor_type',
            field=models.CharField(choices=[('OPTICAL', 'Multispectral / Optical'), ('SAR', 'Synthetic Aperture Radar'), ('HYPERSPECTRAL', 'Hyperspectral'), ('THERMAL', 'Thermal Infrared')], max_length=32),
        ),
        migrations.AlterField(
            model_name='satellitecollection',
            name='spatial_resolution_meters',
            field=models.FloatField(blank=True, help_text='Catalogue-provided nominal spatial resolution.', null=True),
        ),
        migrations.AlterField(
            model_name='satellitecollection',
            name='temporal_revisit_days',
            field=models.FloatField(blank=True, help_text='Catalogue-provided revisit interval, if available.', null=True),
        ),
        migrations.AlterField(
            model_name='satellitescene',
            name='availability_status',
            field=models.CharField(choices=[('CATALOGUED', 'Catalogued in Remote STAC'), ('INDEXED', 'Metadata Locally Indexed'), ('CACHED', 'Assets Cached Locally'), ('ARCHIVED', 'Archived in Cold Storage')], default='CATALOGUED', max_length=32),
        ),
        migrations.AlterField(
            model_name='satellitescene',
            name='bbox',
            field=models.JSONField(blank=True, help_text='[min_x, min_y, max_x, max_y] when supplied.', null=True),
        ),
        migrations.AlterField(
            model_name='satellitescene',
            name='collection',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='satellitescene',
            name='crs',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='satellitescene',
            name='geometry',
            field=models.JSONField(blank=True, help_text='Footprint supplied by the source catalogue.', null=True),
        ),
        migrations.AlterField(
            model_name='satellitescene',
            name='instrument',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='satellitescene',
            name='mission',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='satellitescene',
            name='modality',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='satellitescene',
            name='platform',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='satellitescene',
            name='processing_level',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='satellitescene',
            name='provider',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='satellitescene',
            name='resolution',
            field=models.FloatField(blank=True, help_text='Source-provided spatial resolution in metres.', null=True),
        ),
        migrations.AlterField(
            model_name='satellitescene',
            name='sensor',
            field=models.CharField(choices=[('OPTICAL', 'Optical'), ('SAR', 'Synthetic Aperture Radar'), ('HYPERSPECTRAL', 'Hyperspectral'), ('THERMAL', 'Thermal'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=32),
        ),
        migrations.AlterField(
            model_name='satellitescene',
            name='stac_item_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='satellitescene',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='temporalobservation',
            name='quality_score',
            field=models.FloatField(blank=True, help_text='Only populated when a documented quality metric exists.', null=True),
        ),
        migrations.AddIndex(
            model_name='acquisitioncandidate',
            index=models.Index(fields=['request', 'selected'], name='sat_candidate_req_selected_idx'),
        ),
        migrations.AddIndex(
            model_name='acquisitioncandidate',
            index=models.Index(fields=['stac_item_id'], name='sat_candidate_stac_idx'),
        ),
        migrations.AddIndex(
            model_name='acquisitionrequest',
            index=models.Index(fields=['session', '-created_at'], name='sat_acq_session_created_idx'),
        ),
        migrations.AddIndex(
            model_name='acquisitionrequest',
            index=models.Index(fields=['sensor', 'date_start', 'date_end'], name='sat_acq_sensor_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='acquisitionrequest',
            index=models.Index(fields=['status', '-created_at'], name='sat_acq_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='aoimonitoring',
            index=models.Index(fields=['is_active', 'cadence'], name='sat_monitor_active_cadence_idx'),
        ),
        migrations.AddIndex(
            model_name='aoimonitoring',
            index=models.Index(fields=['aoi', 'is_active'], name='sat_monitor_aoi_active_idx'),
        ),
        migrations.AddIndex(
            model_name='areaofinterest',
            index=models.Index(fields=['session', '-created_at'], name='sat_aoi_session_created_idx'),
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['aoi', '-created_at'], name='sat_change_aoi_created_idx'),
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['change_type', '-created_at'], name='sat_change_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='datasyncjob',
            index=models.Index(fields=['provider', '-start_time'], name='sat_sync_provider_start_idx'),
        ),
        migrations.AddIndex(
            model_name='datasyncjob',
            index=models.Index(fields=['status', '-start_time'], name='sat_sync_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='derivedraster',
            index=models.Index(fields=['scene', 'index_type'], name='sat_derived_scene_type_idx'),
        ),
        migrations.AddIndex(
            model_name='satelliteasset',
            index=models.Index(fields=['scene', 'asset_key'], name='sat_asset_scene_key_idx'),
        ),
        migrations.AddIndex(
            model_name='satelliteasset',
            index=models.Index(fields=['is_downloaded'], name='sat_asset_downloaded_idx'),
        ),
        migrations.AddIndex(
            model_name='satellitecollection',
            index=models.Index(fields=['sensor_type', 'is_active'], name='sat_coll_sensor_act_idx'),
        ),
        migrations.AddIndex(
            model_name='satellitescene',
            index=models.Index(fields=['sensor', '-acquisition_datetime'], name='sat_scene_sensor_date_idx'),
        ),
        migrations.AddIndex(
            model_name='satellitescene',
            index=models.Index(fields=['platform', '-acquisition_datetime'], name='sat_scene_platform_date_idx'),
        ),
        migrations.AddIndex(
            model_name='satellitescene',
            index=models.Index(fields=['availability_status', 'acquisition_datetime'], name='sat_scene_avail_date_idx'),
        ),
        migrations.AddIndex(
            model_name='temporalobservation',
            index=models.Index(fields=['aoi', 'observation_date'], name='sat_obs_aoi_date_idx'),
        ),
        migrations.AddIndex(
            model_name='temporalobservation',
            index=models.Index(fields=['aoi', 'year'], name='sat_obs_aoi_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='acquisitioncandidate',
            constraint=models.UniqueConstraint(fields=('request', 'stac_item_id'), name='sat_candidate_request_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='derivedraster',
            constraint=models.UniqueConstraint(fields=('scene', 'index_type'), name='sat_derived_scene_index_unique'),
        ),
        migrations.AddConstraint(
            model_name='satelliteasset',
            constraint=models.UniqueConstraint(fields=('scene', 'asset_key'), name='sat_asset_scene_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='satellitecollection',
            constraint=models.UniqueConstraint(fields=('provider', 'collection_id'), name='sat_collection_provider_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='satellitescene',
            constraint=models.UniqueConstraint(fields=('provider', 'collection', 'external_id'), name='sat_scene_provider_collection_external_unique'),
        ),
        migrations.AddConstraint(
            model_name='temporalobservation',
            constraint=models.UniqueConstraint(fields=('aoi', 'scene'), name='sat_observation_aoi_scene_unique'),
        ),
    ]
