# Generated by Django 5.1.15 on 2026-09-04 05:15

import apps.imagery.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.imagery.models.image_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=128)),
                ('file_format', models.CharField(choices=[('GEOTIFF', 'GeoTIFF'), ('TIFF', 'TIFF'), ('PNG', 'PNG'), ('JPEG', 'JPEG')], default='GEOTIFF', max_length=32)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('band_count', models.IntegerField(default=1)),
                ('dtype', models.CharField(default='uint8', max_length=64)),
                ('crs', models.CharField(blank=True, max_length=255, null=True)),
                ('affine_transform', models.JSONField(blank=True, null=True)),
                ('bounds_native', models.JSONField(blank=True, null=True)),
                ('bounds_wgs84', models.JSONField(blank=True, null=True)),
                ('resolution_m', models.FloatField(blank=True, null=True)),
                ('sensor', models.CharField(choices=[('SENTINEL-2', 'Sentinel-2'), ('SENTINEL-1', 'Sentinel-1'), ('CARTOSAT-2S', 'Cartosat-2S'), ('RISAT', 'RISAT'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=64)),
                ('modality', models.CharField(choices=[('OPTICAL', 'Optical'), ('MULTISPECTRAL', 'Multispectral'), ('SAR', 'Synthetic Aperture Radar'), ('UNKNOWN', 'Unknown')], default='OPTICAL', max_length=64)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('cloud_cover_pct', models.FloatField(blank=True, null=True)),
                ('is_georeferenced', models.BooleanField(default=False)),
                ('preview_url', models.CharField(blank=True, max_length=512, null=True)),
                ('processing_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('VALIDATED', 'Validated'), ('FAILED', 'Failed')], default='UPLOADED', max_length=32)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagery_assets', to='analysis_sessions.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagePair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pair_type', models.CharField(choices=[('CROSS_MODAL', 'Cross-Modal (Optical + SAR)'), ('BI_TEMPORAL', 'Bi-Temporal (Time T1 + T2)')], max_length=32)),
                ('compatibility_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPATIBLE', 'Compatible'), ('INCOMPATIBLE', 'Incompatible')], default='PENDING', max_length=32)),
                ('compatibility_report', models.JSONField(blank=True, default=dict)),
                ('coregistration_status', models.CharField(choices=[('NOT_NEEDED', 'Not Needed'), ('PENDING', 'Pending'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='NOT_NEEDED', max_length=32)),
                ('coregistered_a_file', models.FileField(blank=True, null=True, upload_to='coregistered/')),
                ('coregistered_b_file', models.FileField(blank=True, null=True, upload_to='coregistered/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_first', to='imagery.imageasset')),
                ('image_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_second', to='imagery.imageasset')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_pairs', to='analysis_sessions.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
