# Generated by Django 5.1.15 on 2026-09-05 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageryArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('GEOTIFF', 'GeoTIFF'), ('RGB_PREVIEW', 'RGB Preview'), ('THUMBNAIL', 'Thumbnail'), ('FALSE_COLOR', 'False Color'), ('CHANGE_MASK', 'Change Mask'), ('CHANGE_PROBABILITY', 'Change Probability'), ('GEOJSON', 'GeoJSON Vector Polygons'), ('EVIDENCE_JSON', 'Evidence JSON Dossier')], max_length=50)),
                ('file', models.FileField(upload_to='artifacts/')),
                ('mime_type', models.CharField(default='image/webp', max_length=100)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('bounds', models.JSONField(blank=True, help_text='Bounding envelope [west, south, east, north]', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='imagery.imageasset')),
                ('image_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_artifacts', to='imagery.imagepair')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
