# Generated by Django 5.1.15 on 2026-09-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_sessions', '0004_alter_session_options_and_more'),
        ('imagery', '0002_imageryartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageryartifact',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='band_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='dtype',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='modality',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('OPTICAL', 'Optical'), ('MULTISPECTRAL', 'Multispectral'), ('SAR', 'Synthetic Aperture Radar'), ('THERMAL', 'Thermal'), ('PAN', 'Panchromatic'), ('HYPERSPECTRAL', 'Hyperspectral')], default='UNKNOWN', max_length=64),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='preview_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='sensor',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SENTINEL-1', 'Sentinel-1'), ('SENTINEL-2', 'Sentinel-2'), ('CARTOSAT-2S', 'Cartosat-2S'), ('RISAT', 'RISAT')], default='UNKNOWN', max_length=64),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageryartifact',
            name='bounds',
            field=models.JSONField(blank=True, help_text='WGS84 bounding envelope [west, south, east, north] when genuinely available.', null=True),
        ),
        migrations.AlterField(
            model_name='imageryartifact',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageryartifact',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', max_length=100),
        ),
        migrations.AlterField(
            model_name='imageryartifact',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='imageasset',
            index=models.Index(fields=['session', '-created_at'], name='imagery_ima_session_693e46_idx'),
        ),
        migrations.AddIndex(
            model_name='imageasset',
            index=models.Index(fields=['processing_status'], name='imagery_ima_process_af3130_idx'),
        ),
        migrations.AddIndex(
            model_name='imageasset',
            index=models.Index(fields=['sensor'], name='imagery_ima_sensor_e69345_idx'),
        ),
        migrations.AddIndex(
            model_name='imageasset',
            index=models.Index(fields=['modality'], name='imagery_ima_modalit_53478f_idx'),
        ),
        migrations.AddIndex(
            model_name='imageasset',
            index=models.Index(fields=['acquisition_date'], name='imagery_ima_acquisi_8791c4_idx'),
        ),
        migrations.AddIndex(
            model_name='imageasset',
            index=models.Index(fields=['is_georeferenced'], name='imagery_ima_is_geor_6f0734_idx'),
        ),
        migrations.AddIndex(
            model_name='imagepair',
            index=models.Index(fields=['session', '-created_at'], name='imagery_ima_session_2c4b19_idx'),
        ),
        migrations.AddIndex(
            model_name='imagepair',
            index=models.Index(fields=['pair_type'], name='imagery_ima_pair_ty_7c0b40_idx'),
        ),
        migrations.AddIndex(
            model_name='imagepair',
            index=models.Index(fields=['compatibility_status'], name='imagery_ima_compati_76aaa0_idx'),
        ),
        migrations.AddIndex(
            model_name='imagepair',
            index=models.Index(fields=['coregistration_status'], name='imagery_ima_coregis_f0fd86_idx'),
        ),
        migrations.AddIndex(
            model_name='imageryartifact',
            index=models.Index(fields=['image_asset', '-created_at'], name='imagery_ima_image_a_d6f1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='imageryartifact',
            index=models.Index(fields=['image_pair', '-created_at'], name='imagery_ima_image_p_0d16b5_idx'),
        ),
        migrations.AddIndex(
            model_name='imageryartifact',
            index=models.Index(fields=['artifact_type'], name='imagery_ima_artifac_eb5535_idx'),
        ),
        migrations.AddConstraint(
            model_name='imagepair',
            constraint=models.CheckConstraint(condition=models.Q(('image_a', models.F('image_b')), _negated=True), name='imagery_pair_distinct_assets'),
        ),
    ]
