# Generated by Django 5.1.15 on 2026-09-04 05:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geojson_geometry', models.JSONField()),
                ('class_name', models.CharField(default='detected_feature', max_length=128)),
                ('confidence', models.FloatField(default=0.0)),
                ('area_m2', models.FloatField(default=0.0)),
                ('area_ha', models.FloatField(default=0.0)),
                ('area_km2', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_regions', to='queries.query')),
                ('source_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_evidence', to='queries.executionstep')),
            ],
            options={
                'ordering': ['-area_km2'],
            },
        ),
    ]
