# Generated by Django 5.1.15 on 2026-09-04 17:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
        ('queries', '0002_query_evidence_graph_query_follow_up_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=1024)),
                ('source_domain', models.CharField(db_index=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('source_type', models.CharField(choices=[('TIER_1_GOV_AGENCY', 'Tier 1: Government & Space Agencies'), ('TIER_2_ACADEMIC_RESEARCH', 'Tier 2: Scientific & Academic Institutions'), ('TIER_3_TRUSTED_NEWS', 'Tier 3: Reputable News & Verified Reports'), ('TIER_4_GENERAL_WEB', 'Tier 4: General Web (Corroborating)')], default='TIER_1_GOV_AGENCY', max_length=64)),
                ('trust_score', models.FloatField(default=0.85)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('summary_facts', models.JSONField(default=list, help_text='List of atomic factual statements')),
                ('content_hash', models.CharField(help_text='SHA-256 hash for audit integrity', max_length=64)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('ttl_expires_at', models.DateTimeField(blank=True, help_text='Ephemeral TTL cache expiration', null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_evidence', to='queries.query')),
            ],
            options={
                'ordering': ['-trust_score', '-retrieved_at'],
            },
        ),
    ]
