# Generated by Django 5.1.15 on 2026-09-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_externalevidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidenceregion',
            options={'ordering': ['-created_at', '-area_km2']},
        ),
        migrations.AlterModelOptions(
            name='externalevidence',
            options={'ordering': ['-retrieved_at', '-trust_score']},
        ),
        migrations.AddField(
            model_name='evidenceregion',
            name='measurements',
            field=models.JSONField(blank=True, default=dict, help_text='Actual measurements produced by the analysis pipeline. Do not use this field for generated estimates.'),
        ),
        migrations.AddField(
            model_name='evidenceregion',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='Additional structured attributes associated with this evidence region.'),
        ),
        migrations.AddField(
            model_name='evidenceregion',
            name='provenance',
            field=models.JSONField(blank=True, default=dict, help_text='Structured provenance describing the source imagery, model/tool, processing operation, and measurement origin.'),
        ),
        migrations.AddField(
            model_name='externalevidence',
            name='provenance',
            field=models.JSONField(blank=True, default=dict, help_text='Additional retrieval and provenance metadata.'),
        ),
        migrations.AlterField(
            model_name='evidenceregion',
            name='area_ha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidenceregion',
            name='area_km2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidenceregion',
            name='area_m2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidenceregion',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidenceregion',
            name='geojson_geometry',
            field=models.JSONField(help_text='GeoJSON geometry produced from verified source imagery. Coordinates must not be fabricated for unreferenced imagery.'),
        ),
        migrations.AlterField(
            model_name='externalevidence',
            name='content_hash',
            field=models.CharField(help_text='SHA-256 hash of the retrieved source content.', max_length=64),
        ),
        migrations.AlterField(
            model_name='externalevidence',
            name='source_type',
            field=models.CharField(choices=[('TIER_1_GOV_AGENCY', 'Tier 1: Government & Space Agencies'), ('TIER_2_ACADEMIC_RESEARCH', 'Tier 2: Scientific & Academic Institutions'), ('TIER_3_TRUSTED_NEWS', 'Tier 3: Reputable News & Verified Reports'), ('TIER_4_GENERAL_WEB', 'Tier 4: General Web (Corroborating)')], default='TIER_4_GENERAL_WEB', max_length=64),
        ),
        migrations.AlterField(
            model_name='externalevidence',
            name='summary_facts',
            field=models.JSONField(blank=True, default=list, help_text='Atomic factual statements extracted from the actual source.'),
        ),
        migrations.AlterField(
            model_name='externalevidence',
            name='trust_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalevidence',
            name='ttl_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
