# Generated by Django 5.1.15 on 2026-09-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_user_organization_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Organization Owner'), ('ADMIN', 'Project Administrator'), ('ANALYST', 'Remote Sensing Analyst'), ('VIEWER', 'Read-Only Viewer'), ('JUDGE', 'SIH Technical Judge'), ('demo', 'Demo Analyst'), ('judge', 'SIH Judge'), ('admin', 'Administrator')], default='ANALYST', max_length=32),
        ),
    ]
