# Generated by Django 5.1.15 on 2026-09-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Organization Owner'), ('ADMIN', 'Project Administrator'), ('ANALYST', 'Remote Sensing Analyst'), ('VIEWER', 'Read-Only Viewer'), ('JUDGE', 'Legacy Judge'), ('demo', 'Legacy Demo Analyst'), ('judge', 'Legacy Judge'), ('admin', 'Legacy Administrator')], default='ANALYST', max_length=32),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['tier', 'created_at'], name='org_tier_created_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', '-created_at'], name='project_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'name'], name='project_org_name_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role'], name='user_org_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'is_active'], name='user_org_active_idx'),
        ),
    ]
