"""Hugging Face BLIP/LoRA runtime for the RS_VQA specialist."""
from __future__ import annotations

from typing import Any


class HuggingFaceRSVQA:
    """Load a local SatQuery RS-VQA checkpoint or a compatible HF model."""

    def __init__(self, model_id: str, device: str = "cpu") -> None:
        try:
            import torch
            from transformers import BlipForQuestionAnswering, BlipProcessor
        except ImportError as exc:
            raise RuntimeError("Install torch and transformers to run a real RS-VQA checkpoint.") from exc

        self.model_id = model_id
        self.device = device
        self.processor = BlipProcessor.from_pretrained(model_id)
        self.model = BlipForQuestionAnswering.from_pretrained(model_id)
        self.model.to(device)
        self.model.eval()
        self._torch = torch

    def answer(self, *, image, question: str, inputs: Any | None = None) -> dict[str, Any]:
        encoded = self.processor(images=image, text=question, return_tensors="pt")
        encoded = {k: v.to(self.device) for k, v in encoded.items()}
        with self._torch.inference_mode():
            generated = self.model.generate(**encoded, max_new_tokens=32)
        answer = self.processor.tokenizer.decode(generated[0], skip_special_tokens=True).strip()
        if not answer:
            raise RuntimeError("RS-VQA checkpoint returned an empty answer.")
        return {
            "answer": answer,
            "provenance": "Generated by the loaded SatQuery RS-VQA checkpoint.",
            "confidence": None,
        }
