# Generated by Django 5.1.15 on 2026-09-04 05:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis_sessions', '0001_initial'),
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('format', models.CharField(choices=[('HTML', 'HTML Document'), ('PDF', 'PDF Document')], default='PDF', max_length=16)),
                ('status', models.CharField(choices=[('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='GENERATING', max_length=32)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='queries.query')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analysis_sessions.session')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
