# Generated by Django 5.1.15 on 2026-09-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_sessions', '0004_alter_session_options_and_more'),
        ('queries', '0003_executionstep_agent_type_executionstep_evidence_refs_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='renderer_version',
            field=models.CharField(default='1.0', max_length=64),
        ),
        migrations.AddField(
            model_name='report',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['session', '-generated_at'], name='reports_session_created_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-generated_at'], name='reports_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['format', '-generated_at'], name='reports_format_created_idx'),
        ),
    ]
