"""
Standard model input/output contracts for SatQuery-X.

This module defines the boundary between orchestration/planning and
actual model/tool execution.

Design principles
-----------------
- Never fabricate imagery, measurements, dates, coordinates, sensors, or
  confidence values.
- Preserve actual model/tool metadata.
- Keep contracts serializable and predictable.
- ModelInput carries runtime evidence/context into a model.
- ModelOutput carries actual model results back to the orchestration layer.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any


@dataclass
class ModelInput:
    """
    Input contract for a SatQuery-X model.

    image_paths:
        Actual filesystem/object-storage paths supplied by the execution layer.

    image_bytes:
        Actual image bytes when a model requires in-memory input.

    question:
        User's actual analytical question.

    text_prompt:
        Optional model-specific prompt generated by the orchestration layer.

    change_mask:
        Existing actual change mask when a downstream model needs it.

    params:
        Explicit model parameters. No scientific defaults should be silently
        inserted here.

    context:
        Runtime context such as spatial metadata, temporal metadata,
        conversation references, evidence references, and asset metadata.
    """

    model_id: str

    image_paths: list[str] = field(default_factory=list)
    image_bytes: list[bytes] = field(default_factory=list)

    question: str | None = None
    text_prompt: str | None = None

    change_mask: str | bytes | None = None

    params: dict[str, Any] = field(default_factory=dict)

    context: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """
        Return a JSON-friendly representation.

        Raw bytes are represented by their length rather than being embedded
        directly into JSON.
        """

        data = asdict(self)

        if self.image_bytes:
            data["image_bytes"] = [
                {
                    "type": "bytes",
                    "size": len(value),
                }
                for value in self.image_bytes
            ]
        else:
            data["image_bytes"] = []

        if isinstance(self.change_mask, bytes):
            data["change_mask"] = {
                "type": "bytes",
                "size": len(self.change_mask),
            }

        return data


@dataclass
class ModelOutput:
    """
    Output contract returned by an actual model/tool.

    A successful output should contain evidence produced by the model.

    Confidence is optional because not every model provides a calibrated
    confidence value.

    No caller should replace missing values with invented defaults.
    """

    model_id: str
    version: str
    task: str

    answer: str | None = None
    caption: str | None = None

    confidence: float | None = None

    boxes: list[dict[str, Any]] | None = None

    change_mask: str | bytes | None = None
    overlay: str | bytes | None = None

    raw: dict[str, Any] | None = None

    latency_ms: int | None = None

    status: str = "ok"
    error: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """
        Serialize the model output without embedding binary payloads.
        """

        data: dict[str, Any] = {
            "model_id": self.model_id,
            "version": self.version,
            "task": self.task,
            "answer": self.answer,
            "caption": self.caption,
            "confidence": self.confidence,
            "boxes": self.boxes,
            "raw": self.raw,
            "latency_ms": self.latency_ms,
            "status": self.status,
            "error": self.error,
        }

        if isinstance(self.change_mask, bytes):
            data["change_mask"] = {
                "type": "bytes",
                "size": len(self.change_mask),
            }
        else:
            data["change_mask"] = self.change_mask

        if isinstance(self.overlay, bytes):
            data["overlay"] = {
                "type": "bytes",
                "size": len(self.overlay),
            }
        else:
            data["overlay"] = self.overlay

        return data

    @property
    def succeeded(self) -> bool:
        """Whether the model reported a successful execution."""

        return self.status.lower() in {
            "ok",
            "success",
            "completed",
            "done",
        }

    @property
    def failed(self) -> bool:
        """Whether the model reported a failed execution."""

        return not self.succeeded