"""
SatQuery-X Evidence-Grounded Query Optimizer
=============================================

The query optimizer converts the output of query understanding into a
structured, execution-ready request.

Pipeline position
-----------------

    User Query
        ↓
    Query Understanding
        ↓
    Query Optimizer          <-- this module
        ↓
    Planner
        ↓
    Executor
        ↓
    Evidence Validation
        ↓
    Response

The optimizer is NOT an analysis engine.

It must never:
- download satellite imagery;
- calculate NDVI/NDWI/NDBI/NBR;
- invent coordinates;
- invent an AOI;
- invent acquisition dates;
- invent a satellite/sensor;
- invent a CRS;
- invent spatial resolution;
- invent measurements;
- invent model confidence;
- fabricate a fallback raster;
- claim that imagery exists when it has not been retrieved;
- treat an arbitrary RGB image as multispectral data;
- claim that two images are temporally comparable without evidence;
- expose chain-of-thought.

It may:
- classify the operational requirement;
- preserve explicit user constraints;
- inherit grounded map/session context;
- identify required measurements;
- identify required modalities;
- identify missing inputs;
- request real satellite/catalogue retrieval;
- determine whether external knowledge is needed;
- prepare a machine-readable plan for the Planner.

Important temporal rule
-----------------------
Relative expressions such as "last 6 months" are recorded as a request.
The optimizer does NOT silently convert them into dates using the current
clock. A temporal resolver/catalogue provider must resolve them later.

"Latest" means:
    latest available observation satisfying the request.

It does NOT mean:
    today,
    last 30 days,
    last 90 days,
    Sentinel-2,
    or any other invented default.

Important spatial rule
---------------------
"here", "this place", "this area", etc. can only resolve if an actual
map/session spatial context exists.

No default city or coordinate is used.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Optional, Tuple

from .query_schema import (
    AnalysisPlanContract,
    ComparisonMode,
    PlanStepContract,
)


# ============================================================================
# Structured optimizer output
# ============================================================================


@dataclass
class StructuredQueryPlan:
    """
    Optimized representation of the user's request.

    Empty dictionaries/lists and None values mean that information has not
    been established. Downstream systems must not interpret them as defaults.
    """

    intent: str

    target: str

    operation: str

    aoi: Dict[str, Any] = field(
        default_factory=dict
    )

    time_range: Dict[str, Any] = field(
        default_factory=dict
    )

    modalities: List[str] = field(
        default_factory=list
    )

    analysis: List[str] = field(
        default_factory=list
    )

    external_evidence_required: bool = False

    external_query: str = ""

    is_follow_up: bool = False

    requested_measurements: List[str] = field(
        default_factory=list
    )

    # Planning threshold only.
    #
    # It is copied only when explicitly configured by the caller.
    # It is never generated by the optimizer.
    confidence_threshold: Optional[float] = None

    uncertainty_notes: List[str] = field(
        default_factory=list
    )

    clarification_prompt: Optional[str] = None

    clarification_options: List[Dict[str, str]] = field(
        default_factory=list
    )

    input_requirements: Dict[str, Any] = field(
        default_factory=dict
    )

    context: Dict[str, Any] = field(
        default_factory=dict
    )

    source: str = "query_optimizer"

    optimizer_version: str = "6.0"

    def to_dict(self) -> Dict[str, Any]:
        """Return a JSON-safe representation."""

        return {
            "intent": self.intent,
            "target": self.target,
            "operation": self.operation,
            "aoi": _json_safe(self.aoi),
            "time_range": _json_safe(self.time_range),
            "modalities": list(self.modalities),
            "analysis": list(self.analysis),
            "external_evidence_required": (
                self.external_evidence_required
            ),
            "external_query": self.external_query,
            "is_follow_up": self.is_follow_up,
            "requested_measurements": list(
                self.requested_measurements
            ),
            "confidence_threshold": (
                self.confidence_threshold
            ),
            "uncertainty_notes": list(
                self.uncertainty_notes
            ),
            "clarification_prompt": (
                self.clarification_prompt
            ),
            "clarification_options": _json_safe(
                self.clarification_options
            ),
            "input_requirements": _json_safe(
                self.input_requirements
            ),
            "context": _json_safe(
                self.context
            ),
            "source": self.source,
            "optimizer_version": self.optimizer_version,
        }

    def to_analysis_plan(
        self,
        steps: Optional[List[PlanStepContract]] = None,
    ) -> AnalysisPlanContract:
        """
        Convert this optimizer result into the shared analysis-plan schema.
        """

        comparison_mode = self._comparison_mode()

        return AnalysisPlanContract(
            intent=self.intent,
            comparison_mode=comparison_mode,
            steps=list(steps or []),
            target=self.target,
            operation=self.operation,
            aoi=dict(self.aoi),
            time_range=dict(self.time_range),
            modalities=list(self.modalities),
            requested_outputs=list(
                self.input_requirements.get(
                    "requested_outputs",
                    [],
                )
                or []
            ),
            requested_measurements=list(
                self.requested_measurements
            ),
            input_requirements=dict(
                self.input_requirements
            ),
            uncertainty_notes=list(
                self.uncertainty_notes
            ),
            clarification_required=bool(
                self.clarification_prompt
            ),
            clarification_prompt=(
                self.clarification_prompt
            ),
            clarification_options=[
                item.get("label", "")
                for item in self.clarification_options
                if isinstance(item, dict)
                and item.get("label")
            ],
            external_evidence_required=(
                self.external_evidence_required
            ),
            external_query=self.external_query,
            is_follow_up=self.is_follow_up,
            context=dict(self.context),
            source=self.source,
            optimizer_version=self.optimizer_version,
        )

    def _comparison_mode(self) -> Optional[str]:
        """Infer semantic comparison mode from the optimized request."""

        if self.intent == "CHANGE_DETECTION":
            return ComparisonMode.MODE_B_CHANGE_DYNAMICS

        if self.intent == "BI_TEMPORAL":
            return ComparisonMode.BI_TEMPORAL

        if self.intent == "CROSS_MODAL":
            return ComparisonMode.CROSS_MODAL

        if self.time_range.get("comparison_required"):
            return ComparisonMode.MODE_B_CHANGE_DYNAMICS

        return ComparisonMode.SINGLE_OBSERVATION


# ============================================================================
# Query optimizer
# ============================================================================


class QueryOptimizer:
    """
    Deterministic optimizer for SatQuery-X.

    The optimizer works primarily from:
    - query text;
    - QueryIntent-like dictionaries/objects;
    - actual session/map context.

    It does not execute tools.
    """

    VERSION = "6.0"

    # ------------------------------------------------------------------
    # Vocabulary
    # ------------------------------------------------------------------

    CHANGE_TERMS = (
        "change",
        "changed",
        "difference",
        "compare",
        "comparison",
        "before and after",
        "evolution",
        "growth",
        "loss",
        "decline",
        "increase",
        "decrease",
        "expanded",
        "expansion",
        "new construction",
        "disappeared",
        "what changed",
        "how did it change",
    )

    VEGETATION_TERMS = (
        "vegetation",
        "vegetation health",
        "agriculture",
        "agricultural",
        "crop",
        "crops",
        "forest",
        "forestry",
        "canopy",
        "trees",
        "tree cover",
        "greenery",
        "plant",
        "plants",
        "ndvi",
        "evi",
    )

    WATER_TERMS = (
        "water",
        "lake",
        "lakes",
        "river",
        "rivers",
        "reservoir",
        "reservoirs",
        "pond",
        "ponds",
        "water body",
        "water bodies",
        "inundation",
        "inundated",
        "flood",
        "flooding",
        "ndwi",
    )

    URBAN_TERMS = (
        "building",
        "buildings",
        "urban",
        "urbanization",
        "urbanisation",
        "construction",
        "structure",
        "structures",
        "road",
        "roads",
        "built-up",
        "built up",
        "ndbi",
    )

    THERMAL_TERMS = (
        "thermal",
        "temperature",
        "land surface temperature",
        "lst",
        "heat",
        "hotspot",
        "thermal anomaly",
    )

    SAR_TERMS = (
        "sar",
        "radar",
        "synthetic aperture radar",
        "backscatter",
        "vv",
        "vh",
        "sar image",
    )

    OPTICAL_TERMS = (
        "optical",
        "multispectral",
        "rgb",
        "visible",
        "spectral",
        "nir",
        "red edge",
    )

    GROUNDING_TERMS = (
        "where is",
        "where are",
        "locate",
        "location of",
        "highlight",
        "find",
        "show me where",
        "mark",
        "ground",
        "grounding",
        "bounding box",
        "bounding boxes",
    )

    LATEST_TERMS = (
        "latest",
        "most recent",
        "recent",
        "newest",
        "currently",
        "current observation",
        "current imagery",
        "near real time",
        "near-real-time",
        "real time",
        "real-time",
        "up to date",
        "up-to-date",
    )

    SATELLITE_TERMS = (
        "satellite",
        "satellite image",
        "satellite imagery",
        "imagery",
        "earth observation",
        "remote sensing",
        "observation",
        "scene",
    )

    WEB_TERMS = (
        "why",
        "reason",
        "cause",
        "official",
        "government",
        "report",
        "reports",
        "policy",
        "announcement",
        "announced",
        "rainfall",
        "precipitation",
        "weather",
        "cyclone",
        "disaster",
        "warning",
        "alert",
        "news",
        "according to",
        "according",
        "explain the cause",
        "historical event",
    )

    TEXT_KNOWLEDGE_TERMS = (
        "what is",
        "what are",
        "how does",
        "how do",
        "explain",
        "meaning of",
        "define",
        "definition",
        "difference between",
    )

    FOLLOW_UP_TERMS = (
        "what about",
        "how about",
        "and what about",
        "how much did",
        "how many of them",
        "which of these",
        "only show",
        "filter",
        "focus on",
        "show changes",
        "show vegetation",
        "show water",
        "show buildings",
        "were they",
        "was it",
        "is it",
        "did it",
        "does it",
        "there",
        "here",
        "this place",
        "this area",
        "that place",
        "that area",
        "same area",
        "same place",
        "same image",
    )

    DEICTIC_TERMS = (
        "here",
        "this place",
        "this area",
        "this location",
        "this point",
        "selected area",
        "selected location",
        "selected point",
        "current map",
        "map area",
        "that place",
        "that area",
        "that location",
        "the selected area",
        "the highlighted area",
        "this scene",
        "this map",
    )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def optimize(
        self,
        text: str,
        session_context: Optional[Dict[str, Any]] = None,
        understanding: Any = None,
    ) -> StructuredQueryPlan:
        """
        Optimize a user request.

        `understanding` may be:
            - QueryIntent
            - QueryUnderstandingContract
            - dict
            - None

        If understanding is supplied, explicit fields from it are preferred
        over re-classifying the query text.
        """

        raw_text = str(text or "").strip()

        context = self._normalize_context(
            session_context
        )

        understanding_data = self._as_dict(
            understanding
        )

        if understanding_data:
            context = self._merge_context(
                context,
                understanding_data.get(
                    "context",
                    {},
                ),
            )

        if not raw_text:
            return self._empty_query_plan(
                context
            )

        q = self._normalize_text(
            raw_text
        )

        # --------------------------------------------------------------
        # Follow-up resolution
        # --------------------------------------------------------------

        is_follow_up = self._detect_follow_up(
            q,
            context,
            understanding_data,
        )

        resolved_query = q

        # Deictic references are resolved by context metadata, not by
        # inventing a location.
        if self._contains_any(
            q,
            self.DEICTIC_TERMS,
        ):
            if self._has_spatial_context(
                context
            ):
                context = self._mark_context_reference(
                    context,
                    "map_spatial_context",
                )

        if is_follow_up:
            context = self._inherit_previous_context(
                context,
            )

        # --------------------------------------------------------------
        # Classification
        # --------------------------------------------------------------

        intent = self._resolve_intent(
            resolved_query,
            understanding_data,
        )

        target = self._resolve_target(
            resolved_query,
            understanding_data,
            context,
        )

        operation = self._resolve_operation(
            resolved_query,
            intent,
            understanding_data,
        )

        modalities = self._resolve_modalities(
            resolved_query,
            understanding_data,
            context,
        )

        aoi = self._resolve_aoi(
            resolved_query,
            understanding_data,
            context,
        )

        time_range = self._resolve_time_range(
            resolved_query,
            understanding_data,
            context,
        )

        measurements = self._requested_measurements(
            resolved_query,
            understanding_data,
        )

        analysis = self._analysis_operations(
            resolved_query,
            intent,
            measurements,
            modalities,
        )

        requested_outputs = self._requested_outputs(
            resolved_query,
            understanding_data,
        )

        # --------------------------------------------------------------
        # External evidence
        # --------------------------------------------------------------

        (
            external_required,
            external_query,
        ) = self._detect_external_necessity(
            resolved_query,
            intent,
            aoi,
            context,
            understanding_data,
        )

        # --------------------------------------------------------------
        # Input requirements
        # --------------------------------------------------------------

        requirements = self._build_input_requirements(
            query=resolved_query,
            intent=intent,
            operation=operation,
            aoi=aoi,
            time_range=time_range,
            modalities=modalities,
            measurements=measurements,
            requested_outputs=requested_outputs,
            context=context,
            external_required=external_required,
        )

        # --------------------------------------------------------------
        # Clarification
        # --------------------------------------------------------------

        (
            clarification_prompt,
            clarification_options,
        ) = self._build_clarification(
            query=resolved_query,
            intent=intent,
            operation=operation,
            aoi=aoi,
            time_range=time_range,
            modalities=modalities,
            measurements=measurements,
            context=context,
            requirements=requirements,
        )

        # --------------------------------------------------------------
        # Uncertainty
        # --------------------------------------------------------------

        uncertainty_notes: List[str] = []

        self._collect_uncertainty(
            query=resolved_query,
            intent=intent,
            aoi=aoi,
            time_range=time_range,
            modalities=modalities,
            measurements=measurements,
            context=context,
            requirements=requirements,
            notes=uncertainty_notes,
        )

        # --------------------------------------------------------------
        # Planning threshold
        # --------------------------------------------------------------

        confidence_threshold = (
            self._configured_confidence_threshold(
                context
            )
        )

        # --------------------------------------------------------------
        # Context snapshot
        # --------------------------------------------------------------

        context_snapshot = (
            self._safe_context_snapshot(
                context
            )
        )

        return StructuredQueryPlan(
            intent=intent,
            target=target,
            operation=operation,
            aoi=aoi,
            time_range=time_range,
            modalities=modalities,
            analysis=analysis,
            external_evidence_required=(
                external_required
            ),
            external_query=external_query,
            is_follow_up=is_follow_up,
            requested_measurements=measurements,
            confidence_threshold=confidence_threshold,
            uncertainty_notes=(
                self._unique(
                    uncertainty_notes
                )
            ),
            clarification_prompt=(
                clarification_prompt
            ),
            clarification_options=(
                clarification_options
            ),
            input_requirements={
                **requirements,
                "requested_outputs": requested_outputs,
                "analysis_requested": analysis,
            },
            context=context_snapshot,
            source="query_optimizer",
            optimizer_version=self.VERSION,
        )

    # ------------------------------------------------------------------
    # Intent resolution
    # ------------------------------------------------------------------

    def _resolve_intent(
        self,
        query: str,
        understanding: Dict[str, Any],
    ) -> str:
        explicit = understanding.get(
            "intent"
        )

        if explicit:
            normalized = str(
                explicit
            ).strip().upper()

            aliases = {
                "CHANGE": "CHANGE_DETECTION",
                "COMPARE": "CHANGE_DETECTION",
                "COMPARISON": "CHANGE_DETECTION",
                "VEGETATION": "VEGETATION_ANALYSIS",
                "WATER": "WATER_DETECTION",
                "URBAN": "URBAN_ANALYSIS",
                "SAR": "SAR_ANALYSIS",
                "THERMAL": "THERMAL_ANALYSIS",
                "OPTICAL_SAR": "OPTICAL_SAR_FUSION",
                "FUSION": "OPTICAL_SAR_FUSION",
                "LATEST": "LATEST_OBSERVATION",
                "SATELLITE": "SATELLITE_SEARCH",
                "TEXT": "TEXT_KNOWLEDGE",
                "WEB": "WEB_KNOWLEDGE",
            }

            return aliases.get(
                normalized,
                normalized,
            )

        # Most specific checks first.

        if self._is_cross_modal_query(
            query
        ):
            return "OPTICAL_SAR_FUSION"

        if self._is_change_query(
            query
        ):
            return "CHANGE_DETECTION"

        if self._is_grounding_query(
            query
        ):
            return "GROUNDING"

        if self._is_vegetation_query(
            query
        ):
            return "VEGETATION_ANALYSIS"

        if self._is_water_query(
            query
        ):
            return "WATER_DETECTION"

        if self._is_urban_query(
            query
        ):
            return "URBAN_ANALYSIS"

        if self._is_thermal_query(
            query
        ):
            return "THERMAL_ANALYSIS"

        if self._is_sar_query(
            query
        ):
            return "SAR_ANALYSIS"

        if self._is_latest_query(
            query
        ):
            return "LATEST_OBSERVATION"

        if self._is_web_query(
            query
        ):
            return "WEB_KNOWLEDGE"

        if self._is_satellite_query(
            query
        ):
            return "SATELLITE_SEARCH"

        if self._is_text_knowledge_query(
            query
        ):
            return "TEXT_KNOWLEDGE"

        if self._contains_any(
            query,
            (
                "caption",
                "describe this image",
                "describe the image",
                "describe the scene",
            ),
        ):
            return "CAPTION"

        if self._contains_any(
            query,
            (
                "what is shown",
                "what do you see",
                "what can you see",
                "identify",
                "analyze this image",
            ),
        ):
            return "VQA"

        return "VQA"

    # ------------------------------------------------------------------
    # Target
    # ------------------------------------------------------------------

    def _resolve_target(
        self,
        query: str,
        understanding: Dict[str, Any],
        context: Dict[str, Any],
    ) -> str:
        target = understanding.get(
            "target"
        )

        if target:
            return str(
                target
            ).strip()

        subject = understanding.get(
            "subject"
        )

        if isinstance(
            subject,
            Mapping,
        ):
            for key in (
                "name",
                "label",
                "target",
                "type",
            ):
                value = subject.get(key)

                if value:
                    return str(
                        value
                    ).strip()

        last_target = context.get(
            "last_target"
        )

        if last_target and self._contains_any(
            query,
            self.FOLLOW_UP_TERMS,
        ):
            return str(
                last_target
            ).strip()

        if self._is_vegetation_query(
            query
        ):
            return "vegetation"

        if self._is_water_query(
            query
        ):
            return "water"

        if self._is_urban_query(
            query
        ):
            return "urban_features"

        if self._is_thermal_query(
            query
        ):
            return "thermal_surface"

        if self._is_sar_query(
            query
        ):
            return "sar_observation"

        if self._is_change_query(
            query
        ):
            return "land_surface_change"

        return "image_or_area"

    # ------------------------------------------------------------------
    # Operation
    # ------------------------------------------------------------------

    def _resolve_operation(
        self,
        query: str,
        intent: str,
        understanding: Dict[str, Any],
    ) -> str:
        explicit = understanding.get(
            "operation"
        )

        if explicit:
            return str(
                explicit
            ).strip()

        operations = {
            "CHANGE_DETECTION": "compare_observations",
            "OPTICAL_SAR_FUSION": "fuse_modalities",
            "VEGETATION_ANALYSIS": "analyze_vegetation",
            "WATER_DETECTION": "detect_water",
            "URBAN_ANALYSIS": "analyze_urban_features",
            "THERMAL_ANALYSIS": "analyze_thermal_signal",
            "SAR_ANALYSIS": "analyze_sar_signal",
            "GROUNDING": "ground_text_in_image",
            "LATEST_OBSERVATION": "retrieve_latest_observation",
            "SATELLITE_SEARCH": "search_satellite_catalog",
            "WEB_KNOWLEDGE": "retrieve_external_knowledge",
            "TEXT_KNOWLEDGE": "understand_text_request",
            "CAPTION": "describe_scene",
            "VQA": "answer_image_question",
        }

        return operations.get(
            intent,
            "analyze_request",
        )

    # ------------------------------------------------------------------
    # Modalities
    # ------------------------------------------------------------------

    def _resolve_modalities(
        self,
        query: str,
        understanding: Dict[str, Any],
        context: Dict[str, Any],
    ) -> List[str]:
        result: List[str] = []

        explicit = understanding.get(
            "modalities"
        )

        if isinstance(
            explicit,
            Mapping,
        ):
            for key in (
                "requested",
                "required",
                "available",
            ):
                value = explicit.get(
                    key
                )

                if isinstance(
                    value,
                    (list, tuple, set),
                ):
                    result.extend(
                        self._normalize_modalities(
                            value
                        )
                    )

                elif isinstance(
                    value,
                    str,
                ):
                    result.extend(
                        self._normalize_modalities(
                            [value]
                        )
                    )

        elif isinstance(
            explicit,
            (list, tuple, set),
        ):
            result.extend(
                self._normalize_modalities(
                    explicit
                )
            )

        if self._contains_any(
            query,
            self.OPTICAL_TERMS,
        ):
            result.append(
                "optical"
            )

        if self._contains_any(
            query,
            self.SAR_TERMS,
        ):
            result.append(
                "sar"
            )

        if self._contains_any(
            query,
            self.THERMAL_TERMS,
        ):
            result.append(
                "thermal"
            )

        context_modalities = (
            context.get(
                "modalities"
            )
        )

        if isinstance(
            context_modalities,
            (list, tuple, set),
        ):
            result.extend(
                self._normalize_modalities(
                    context_modalities
                )
            )

        return self._unique(
            result
        )

    # ------------------------------------------------------------------
    # Spatial
    # ------------------------------------------------------------------

    def _resolve_aoi(
        self,
        query: str,
        understanding: Dict[str, Any],
        context: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Resolve only actual spatial information.

        Priority:
            1. explicit understanding location/spatial data
            2. explicit coordinates / bbox in context
            3. active map pin
            4. selected/current AOI
            5. viewport if explicitly provided

        Natural-language place names are preserved as unresolved names.
        Geocoding belongs to the location resolver, not this optimizer.
        """

        location = understanding.get(
            "location"
        )

        if isinstance(
            location,
            Mapping,
        ):
            resolved = self._clean_spatial_dict(
                location
            )

            if resolved:
                return resolved

        spatial = understanding.get(
            "spatial"
        )

        if isinstance(
            spatial,
            Mapping,
        ):
            resolved = self._clean_spatial_dict(
                spatial
            )

            if resolved:
                return resolved

        # Explicit query coordinates.
        coordinates = self._extract_coordinates(
            query
        )

        if coordinates:
            return {
                "type": "POINT",
                "coordinates": coordinates,
                "source": "query",
                "resolved": True,
            }

        bbox = self._extract_bbox(
            query
        )

        if bbox:
            return {
                "type": "BBOX",
                "bbox": bbox,
                "source": "query",
                "resolved": True,
            }

        # Active map context.
        for key in (
            "active_map_pin",
            "map_pin",
            "selected_map_pin",
            "current_map_pin",
        ):
            value = context.get(
                key
            )

            if isinstance(
                value,
                Mapping,
            ):
                spatial_value = self._clean_spatial_dict(
                    value
                )

                if spatial_value:
                    spatial_value.setdefault(
                        "source",
                        "map_context",
                    )
                    return spatial_value

        # Existing AOI.
        for key in (
            "active_aoi",
            "selected_aoi",
            "current_aoi",
            "aoi",
        ):
            value = context.get(
                key
            )

            if isinstance(
                value,
                Mapping,
            ):
                spatial_value = self._clean_spatial_dict(
                    value
                )

                if spatial_value:
                    spatial_value.setdefault(
                        "source",
                        "session_context",
                    )
                    return spatial_value

        # Explicit viewport.
        viewport = context.get(
            "current_viewport"
        )

        if isinstance(
            viewport,
            Mapping,
        ):
            spatial_value = self._clean_spatial_dict(
                viewport
            )

            if spatial_value:
                spatial_value.setdefault(
                    "source",
                    "map_viewport",
                )
                return spatial_value

        # Preserve unresolved named location if understanding found one.
        name = (
            location.get("name")
            if isinstance(
                location,
                Mapping,
            )
            else None
        )

        if name:
            return {
                "type": "PLACE",
                "name": str(name),
                "resolved": False,
                "source": "query_understanding",
            }

        return {}

    # ------------------------------------------------------------------
    # Temporal
    # ------------------------------------------------------------------

    def _resolve_time_range(
        self,
        query: str,
        understanding: Dict[str, Any],
        context: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Preserve temporal semantics without inventing calendar values.
        """

        explicit = understanding.get(
            "time_range"
        )

        if isinstance(
            explicit,
            Mapping,
        ) and explicit:
            return self._normalize_time_range(
                explicit,
                source="query_understanding",
            )

        temporal = understanding.get(
            "temporal"
        )

        if isinstance(
            temporal,
            Mapping,
        ):
            nested = temporal.get(
                "range"
            )

            if isinstance(
                nested,
                Mapping,
            ):
                return self._normalize_time_range(
                    nested,
                    source="query_understanding",
                )

        # Explicit ISO dates in the query.
        iso_dates = re.findall(
            r"\b(20\d{2}-\d{1,2}-\d{1,2})\b",
            query,
        )

        if len(iso_dates) >= 2:
            start, end = sorted(
                iso_dates[:2]
            )

            return {
                "start": start,
                "end": end,
                "start_date": start,
                "end_date": end,
                "mode": "EXPLICIT_DATE_RANGE",
                "source": "query",
                "requires_provider_resolution": False,
                "comparison_required": True,
            }

        if len(iso_dates) == 1:
            value = iso_dates[0]

            return {
                "start": value,
                "end": value,
                "start_date": value,
                "end_date": value,
                "mode": "EXPLICIT_DATE",
                "source": "query",
                "requires_provider_resolution": False,
                "comparison_required": False,
            }

        # Explicit years.
        years = [
            int(value)
            for value in re.findall(
                r"\b(19\d{2}|20\d{2})\b",
                query,
            )
        ]

        if len(years) >= 2:
            y1, y2 = sorted(
                years[:2]
            )

            return {
                "start": f"{y1:04d}-01-01",
                "end": f"{y2:04d}-12-31",
                "start_date": f"{y1:04d}-01-01",
                "end_date": f"{y2:04d}-12-31",
                "mode": "EXPLICIT_YEAR_RANGE",
                "source": "query",
                "requires_provider_resolution": False,
                "comparison_required": True,
            }

        if len(years) == 1:
            year = years[0]

            return {
                "start": f"{year:04d}-01-01",
                "end": f"{year:04d}-12-31",
                "start_date": f"{year:04d}-01-01",
                "end_date": f"{year:04d}-12-31",
                "mode": "EXPLICIT_YEAR",
                "source": "query",
                "requires_provider_resolution": False,
                "comparison_required": False,
            }

        # Relative ranges are preserved, NOT converted to dates here.
        relative = re.search(
            r"\b(?:last|past|previous|over\s+the\s+last|"
            r"over\s+the\s+past)\s+"
            r"(\d+)\s+"
            r"(day|days|week|weeks|month|months|year|years)\b",
            query,
        )

        if relative:
            amount = int(
                relative.group(1)
            )

            unit = relative.group(2)

            if amount > 0:
                return {
                    "start": None,
                    "end": None,
                    "start_date": None,
                    "end_date": None,
                    "mode": "EXPLICIT_RELATIVE_RANGE",
                    "amount": amount,
                    "unit": unit,
                    "source": "query",
                    "requires_provider_resolution": True,
                    "comparison_required": (
                        self._is_change_query(
                            query
                        )
                    ),
                }

        # Latest/current must remain unresolved until a real catalogue
        # provider selects an actual observation.
        if self._is_latest_query(
            query
        ):
            return {
                "start": None,
                "end": None,
                "start_date": None,
                "end_date": None,
                "mode": "LATEST_AVAILABLE",
                "source": "query",
                "requires_provider_resolution": True,
                "comparison_required": False,
            }

        # Use actual image acquisition dates if supplied.
        image_time = self._image_temporal_context(
            context
        )

        if image_time:
            return image_time

        # Existing session temporal context.
        for key in (
            "active_time_range",
            "time_range",
            "temporal_context",
            "date_range",
        ):
            value = context.get(
                key
            )

            if isinstance(
                value,
                Mapping,
            ) and value:
                normalized = (
                    self._normalize_time_range(
                        value,
                        source="session_context",
                    )
                )

                if normalized:
                    return normalized

        if self._is_change_query(
            query
        ):
            return {
                "start": None,
                "end": None,
                "start_date": None,
                "end_date": None,
                "mode": "UNRESOLVED_COMPARISON",
                "source": "query",
                "requires_provider_resolution": True,
                "comparison_required": True,
            }

        return {}

    # ------------------------------------------------------------------
    # Measurements
    # ------------------------------------------------------------------

    def _requested_measurements(
        self,
        query: str,
        understanding: Dict[str, Any],
    ) -> List[str]:
        result: List[str] = []

        explicit = understanding.get(
            "requested_measurements"
        )

        if isinstance(
            explicit,
            (list, tuple, set),
        ):
            result.extend(
                str(value).strip().lower()
                for value in explicit
                if str(value).strip()
            )

        measurement_terms = {
            "ndvi": "ndvi",
            "ndwi": "ndwi",
            "ndbi": "ndbi",
            "nbr": "nbr",
            "evi": "evi",
            "area": "area",
            "area change": "area_change",
            "changed area": "changed_area",
            "percentage": "percentage",
            "percentage change": "percentage_change",
            "percent change": "percentage_change",
            "distance": "distance",
            "count": "count",
            "number of buildings": "feature_count",
            "number of structures": "feature_count",
            "how many buildings": "feature_count",
            "how many structures": "feature_count",
            "temperature": "temperature",
            "surface temperature": "land_surface_temperature",
        }

        for phrase, measurement in measurement_terms.items():
            if phrase in query:
                result.append(
                    measurement
                )

        return self._unique(
            result
        )

    # ------------------------------------------------------------------
    # Analysis operations
    # ------------------------------------------------------------------

    def _analysis_operations(
        self,
        query: str,
        intent: str,
        measurements: List[str],
        modalities: List[str],
    ) -> List[str]:
        operations: List[str] = []

        if intent == "CHANGE_DETECTION":
            operations.append(
                "change_detection"
            )

        if intent == "OPTICAL_SAR_FUSION":
            operations.append(
                "optical_sar_fusion"
            )

        if intent == "VEGETATION_ANALYSIS":
            operations.append(
                "vegetation_detection"
            )

        if intent == "WATER_DETECTION":
            operations.append(
                "water_detection"
            )

        if intent == "URBAN_ANALYSIS":
            operations.append(
                "urban_feature_detection"
            )

        if intent == "THERMAL_ANALYSIS":
            operations.append(
                "thermal_analysis"
            )

        if intent == "SAR_ANALYSIS":
            operations.append(
                "sar_analysis"
            )

        if intent == "GROUNDING":
            operations.append(
                "text_grounding"
            )

        if any(
            value in measurements
            for value in (
                "ndvi",
                "ndwi",
                "ndbi",
                "nbr",
                "evi",
            )
        ):
            operations.append(
                "spectral_index"
            )

        if "area" in measurements or (
            "area_change" in measurements
        ):
            operations.append(
                "area_quantification"
            )

        if "percentage_change" in measurements:
            operations.append(
                "change_percentage"
            )

        if "distance" in measurements:
            operations.append(
                "spatial_measurement"
            )

        if modalities:
            operations.append(
                "modality_specific_analysis"
            )

        return self._unique(
            operations
        )

    # ------------------------------------------------------------------
    # External evidence
    # ------------------------------------------------------------------

    def _detect_external_necessity(
        self,
        query: str,
        intent: str,
        aoi: Dict[str, Any],
        context: Dict[str, Any],
        understanding: Dict[str, Any],
    ) -> Tuple[bool, str]:
        explicit = understanding.get(
            "external_evidence_required"
        )

        if explicit is True:
            external_query = str(
                understanding.get(
                    "external_query",
                    query,
                )
                or query
            )

            return True, external_query

        if intent == "WEB_KNOWLEDGE":
            return True, query

        if self._is_web_query(
            query
        ):
            return True, query

        # Satellite catalogue retrieval is NOT web knowledge.
        #
        # It is handled through the satellite/data provider pipeline.
        return False, ""

    # ------------------------------------------------------------------
    # Input requirements
    # ------------------------------------------------------------------

    def _build_input_requirements(
        self,
        query: str,
        intent: str,
        operation: str,
        aoi: Dict[str, Any],
        time_range: Dict[str, Any],
        modalities: List[str],
        measurements: List[str],
        requested_outputs: List[str],
        context: Dict[str, Any],
        external_required: bool,
    ) -> Dict[str, Any]:
        image_count = self._image_count(
            context
        )

        has_georeferencing = (
            self._has_georeferencing(
                context
            )
        )

        has_band_metadata = (
            self._has_band_metadata(
                context
            )
        )

        requirements: Dict[str, Any] = {
            "intent": intent,
            "operation": operation,
            "available_image_count": image_count,
            "requires_real_evidence": (
                intent
                not in {
                    "TEXT_KNOWLEDGE",
                }
            ),
            "requires_external_web_evidence": (
                external_required
            ),
            "spatial_context_available": bool(
                self._aoi_is_resolved(
                    aoi
                )
            ),
            "temporal_context_available": bool(
                time_range
            ),
            "requested_outputs": requested_outputs,
        }

        # --------------------------------------------------------------
        # Image requirements
        # --------------------------------------------------------------

        if intent in {
            "VQA",
            "CAPTION",
            "GROUNDING",
            "VEGETATION_ANALYSIS",
            "WATER_DETECTION",
            "URBAN_ANALYSIS",
            "THERMAL_ANALYSIS",
            "SAR_ANALYSIS",
        }:
            requirements[
                "requires_image"
            ] = True

        if intent == "CHANGE_DETECTION":
            requirements[
                "requires_two_comparable_observations"
            ] = True

            requirements[
                "required_image_count"
            ] = 2

            requirements[
                "requires_temporal_relationship"
            ] = True

        if intent == "OPTICAL_SAR_FUSION":
            requirements[
                "requires_optical_and_sar"
            ] = True

            requirements[
                "required_image_count"
            ] = 2

        # --------------------------------------------------------------
        # Spectral requirements
        # --------------------------------------------------------------

        spectral = {
            "ndvi",
            "ndwi",
            "ndbi",
            "nbr",
            "evi",
        }

        if spectral.intersection(
            set(measurements)
        ):
            requirements[
                "requires_required_spectral_bands"
            ] = True

            requirements[
                "band_metadata_available"
            ] = has_band_metadata

            requirements[
                "band_mapping_must_be_verified"
            ] = True

        # --------------------------------------------------------------
        # Georeferencing
        # --------------------------------------------------------------

        if any(
            measurement in measurements
            for measurement in (
                "area",
                "area_change",
                "distance",
            )
        ):
            requirements[
                "requires_georeferenced_measurement"
            ] = True

            requirements[
                "georeferencing_available"
            ] = has_georeferencing

        # --------------------------------------------------------------
        # Temporal resolution
        # --------------------------------------------------------------

        if time_range.get(
            "requires_provider_resolution"
        ):
            requirements[
                "temporal_provider_resolution_required"
            ] = True

        if time_range.get(
            "mode"
        ) == "LATEST_AVAILABLE":
            requirements[
                "catalog_latest_resolution_required"
            ] = True

        if time_range.get(
            "mode"
        ) == "EXPLICIT_RELATIVE_RANGE":
            requirements[
                "relative_time_resolution_required"
            ] = True

        # --------------------------------------------------------------
        # Satellite retrieval
        # --------------------------------------------------------------

        satellite_required = (
            intent in {
                "LATEST_OBSERVATION",
                "SATELLITE_SEARCH",
            }
            or (
                intent == "CHANGE_DETECTION"
                and image_count < 2
            )
        )

        if satellite_required:
            requirements[
                "requires_satellite_catalogue"
            ] = True

            requirements[
                "requires_real_satellite_observation"
            ] = True

        # Existing two images mean retrieval is not automatically required.
        if (
            intent == "CHANGE_DETECTION"
            and image_count >= 2
        ):
            requirements[
                "requires_satellite_catalogue"
            ] = False

        # --------------------------------------------------------------
        # Cross-modal availability
        # --------------------------------------------------------------

        if intent == "OPTICAL_SAR_FUSION":
            context_modalities = set(
                self._context_modalities(
                    context
                )
            )

            requirements[
                "optical_available"
            ] = "optical" in context_modalities

            requirements[
                "sar_available"
            ] = "sar" in context_modalities

        return requirements

    # ------------------------------------------------------------------
    # Clarification
    # ------------------------------------------------------------------

    def _build_clarification(
        self,
        query: str,
        intent: str,
        operation: str,
        aoi: Dict[str, Any],
        time_range: Dict[str, Any],
        modalities: List[str],
        measurements: List[str],
        context: Dict[str, Any],
        requirements: Dict[str, Any],
    ) -> Tuple[
        Optional[str],
        List[Dict[str, str]],
    ]:
        """
        Return clarification only when execution cannot safely proceed.

        Important:
        Lack of uploaded imagery alone does not necessarily require
        clarification because real satellite retrieval may satisfy the
        requirement if sufficient spatial/temporal constraints exist.
        """

        # Empty/unknown request.
        if intent in {
            "",
            "UNKNOWN",
        }:
            return (
                "What would you like me to analyze?",
                [
                    {
                        "label": "Analyze the uploaded image",
                        "value": "analyze the uploaded image",
                    },
                    {
                        "label": "Compare two observations",
                        "value": "compare two observations",
                    },
                    {
                        "label": "Find the latest satellite imagery",
                        "value": "find the latest satellite imagery",
                    },
                ],
            )

        # --------------------------------------------------------------
        # Image-dependent analysis
        # --------------------------------------------------------------

        if intent in {
            "VQA",
            "CAPTION",
            "GROUNDING",
            "VEGETATION_ANALYSIS",
            "WATER_DETECTION",
            "URBAN_ANALYSIS",
            "THERMAL_ANALYSIS",
            "SAR_ANALYSIS",
        }:
            if self._image_count(
                context
            ) == 0:
                # If the user supplied a resolvable area, retrieval can
                # potentially provide actual imagery.
                if self._aoi_is_resolved(
                    aoi
                ):
                    return (
                        None,
                        [],
                    )

                # A named place that has not been geocoded is insufficient.
                if aoi.get(
                    "type"
                ) == "PLACE":
                    return (
                        "I can analyze satellite imagery for that place, "
                        "but the location has not yet been resolved to a "
                        "verified geographic area.",
                        [
                            {
                                "label": "Use the selected map area",
                                "value": "use selected map area",
                            },
                            {
                                "label": "Provide coordinates",
                                "value": "provide coordinates",
                            },
                        ],
                    )

                return (
                    "Please upload an image or select a verified area on "
                    "the map so I can analyze real imagery.",
                    [
                        {
                            "label": "Upload an image",
                            "value": "upload an image",
                        },
                        {
                            "label": "Select an area on the map",
                            "value": "select an area on the map",
                        },
                    ],
                )

        # --------------------------------------------------------------
        # Change detection
        # --------------------------------------------------------------

        if intent == "CHANGE_DETECTION":
            if self._image_count(
                context
            ) >= 2:
                return (
                    None,
                    [],
                )

            if self._aoi_is_resolved(
                aoi
            ):
                # Retrieval can search for the two actual observations.
                return (
                    None,
                    [],
                )

            return (
                "To compare change, I need two comparable observations "
                "or a verified area where the required observations can "
                "be retrieved. Please select an area on the map or provide "
                "the location.",
                [
                    {
                        "label": "Select an area on the map",
                        "value": "select an area on the map",
                    },
                    {
                        "label": "Provide coordinates",
                        "value": "provide coordinates",
                    },
                ],
            )

        # --------------------------------------------------------------
        # Optical + SAR
        # --------------------------------------------------------------

        if intent == "OPTICAL_SAR_FUSION":
            context_modalities = set(
                self._context_modalities(
                    context
                )
            )

            if (
                "optical" in context_modalities
                and "sar" in context_modalities
            ):
                return (
                    None,
                    [],
                )

            if self._aoi_is_resolved(
                aoi
            ):
                # Provider may retrieve the required modalities.
                return (
                    None,
                    [],
                )

            return (
                "Optical-SAR fusion requires verified optical and SAR "
                "observations covering the same area. Please select an "
                "area on the map or provide a verified location.",
                [
                    {
                        "label": "Select an area on the map",
                        "value": "select an area on the map",
                    },
                    {
                        "label": "Upload optical and SAR images",
                        "value": "upload optical and SAR images",
                    },
                ],
            )

        # --------------------------------------------------------------
        # Area measurements
        # --------------------------------------------------------------

        if any(
            measurement in measurements
            for measurement in (
                "area",
                "area_change",
                "distance",
            )
        ):
            if not self._has_georeferencing(
                context
            ):
                # Do not reject immediately if retrieval can supply
                # georeferenced satellite imagery.
                if self._aoi_is_resolved(
                    aoi
                ):
                    return (
                        None,
                        [],
                    )

                return (
                    "A spatial measurement requires imagery with verified "
                    "georeferencing. Please provide a georeferenced image "
                    "or select a verified geographic area.",
                    [
                        {
                            "label": "Select an area on the map",
                            "value": "select an area on the map",
                        },
                        {
                            "label": "Upload a georeferenced image",
                            "value": "upload a georeferenced image",
                        },
                    ],
                )

        return (
            None,
            [],
        )

    # ------------------------------------------------------------------
    # Uncertainty
    # ------------------------------------------------------------------

    def _collect_uncertainty(
        self,
        query: str,
        intent: str,
        aoi: Dict[str, Any],
        time_range: Dict[str, Any],
        modalities: List[str],
        measurements: List[str],
        context: Dict[str, Any],
        requirements: Dict[str, Any],
        notes: List[str],
    ) -> None:
        if not self._aoi_is_resolved(
            aoi
        ):
            if intent in {
                "LATEST_OBSERVATION",
                "SATELLITE_SEARCH",
                "CHANGE_DETECTION",
                "OPTICAL_SAR_FUSION",
                "VEGETATION_ANALYSIS",
                "WATER_DETECTION",
                "URBAN_ANALYSIS",
                "THERMAL_ANALYSIS",
                "SAR_ANALYSIS",
            }:
                notes.append(
                    "No verified geographic area is currently available."
                )

        if intent == "CHANGE_DETECTION":
            if self._image_count(
                context
            ) < 2:
                notes.append(
                    "A change analysis requires two comparable observations "
                    "or retrieval of two suitable observations."
                )

            if not time_range:
                notes.append(
                    "No explicit comparison dates were established."
                )

        if intent == "OPTICAL_SAR_FUSION":
            if len(
                modalities
            ) < 2:
                notes.append(
                    "The required optical and SAR modalities have not both "
                    "been established."
                )

        if any(
            measurement in measurements
            for measurement in (
                "ndvi",
                "ndwi",
                "ndbi",
                "nbr",
                "evi",
            )
        ):
            if not self._has_band_metadata(
                context
            ):
                notes.append(
                    "Required spectral band mapping has not yet been "
                    "verified from the available imagery metadata."
                )

        if any(
            measurement in measurements
            for measurement in (
                "area",
                "area_change",
                "distance",
            )
        ):
            if not self._has_georeferencing(
                context
            ):
                notes.append(
                    "Verified georeferencing is required before spatial "
                    "measurements can be reported."
                )

        if time_range.get(
            "requires_provider_resolution"
        ):
            notes.append(
                "The requested temporal expression must be resolved by "
                "the temporal/catalogue layer."
            )

        if time_range.get(
            "mode"
        ) == "LATEST_AVAILABLE":
            notes.append(
                "Latest observation availability must be determined by "
                "the satellite data provider."
            )

    # ------------------------------------------------------------------
    # Follow-up context
    # ------------------------------------------------------------------

    def _detect_follow_up(
        self,
        query: str,
        context: Dict[str, Any],
        understanding: Dict[str, Any],
    ) -> bool:
        if understanding.get(
            "is_follow_up"
        ) is True:
            return True

        if not context.get(
            "last_query"
        ) and not context.get(
            "last_query_id"
        ) and not context.get(
            "conversation_history"
        ):
            # Deictic map references can still be meaningful if map
            # context exists.
            return (
                self._contains_any(
                    query,
                    self.DEICTIC_TERMS,
                )
                and self._has_spatial_context(
                    context
                )
            )

        return self._contains_any(
            query,
            self.FOLLOW_UP_TERMS,
        )

    def _inherit_previous_context(
        self,
        context: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Preserve already-grounded context.

        We copy only references; we do not create new observations.
        """

        result = dict(
            context
        )

        previous = context.get(
            "previous_context"
        )

        if isinstance(
            previous,
            Mapping,
        ):
            for key in (
                "active_aoi",
                "selected_aoi",
                "current_aoi",
                "map_pin",
                "active_map_pin",
                "selected_map_pin",
                "current_viewport",
                "modalities",
                "image_count",
                "images",
                "image_assets",
                "time_range",
                "active_time_range",
                "temporal_context",
                "conversation_location",
                "resolved_location",
                "last_target",
                "last_intent",
            ):
                if (
                    key not in result
                    and key in previous
                ):
                    result[key] = previous[key]

        return result

    # ------------------------------------------------------------------
    # Context handling
    # ------------------------------------------------------------------

    def _normalize_context(
        self,
        context: Optional[Dict[str, Any]],
    ) -> Dict[str, Any]:
        if not isinstance(
            context,
            Mapping,
        ):
            return {}

        return dict(
            context
        )

    def _merge_context(
        self,
        first: Dict[str, Any],
        second: Any,
    ) -> Dict[str, Any]:
        result = dict(
            first
        )

        if not isinstance(
            second,
            Mapping,
        ):
            return result

        for key, value in second.items():
            if key not in result:
                result[key] = value
                continue

            if result[key] in (
                None,
                "",
                [],
                {},
            ):
                result[key] = value

        return result

    def _mark_context_reference(
        self,
        context: Dict[str, Any],
        reference: str,
    ) -> Dict[str, Any]:
        result = dict(
            context
        )

        references = list(
            result.get(
                "resolved_references",
                [],
            )
            or []
        )

        if reference not in references:
            references.append(
                reference
            )

        result[
            "resolved_references"
        ] = references

        return result

    # ------------------------------------------------------------------
    # Safe context snapshot
    # ------------------------------------------------------------------

    def _safe_context_snapshot(
        self,
        context: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Preserve only compact JSON-safe context.

        Raw image arrays/bytes/file objects are deliberately excluded.
        """

        allowed_keys = {
            "session_id",
            "project_id",
            "query_id",
            "active_aoi",
            "selected_aoi",
            "current_aoi",
            "aoi",
            "map_pin",
            "active_map_pin",
            "selected_map_pin",
            "current_map_pin",
            "current_viewport",
            "modalities",
            "image_count",
            "has_images",
            "external_evidence_required",
            "confidence_threshold",
            "time_range",
            "temporal_context",
            "active_time_range",
            "date_range",
            "conversation_location",
            "resolved_location",
            "last_target",
            "last_intent",
            "last_query_id",
            "last_query",
            "last_answer",
            "resolved_references",
            "selected_sensor",
            "sensor",
        }

        result: Dict[str, Any] = {}

        for key in allowed_keys:
            if key not in context:
                continue

            value = context[key]

            # Never put raw image data into a query plan.
            if key in {
                "images",
                "image_assets",
                "uploaded_images",
                "assets",
                "bytes",
                "arrays",
                "image_bytes",
            }:
                continue

            safe = _json_safe(
                value
            )

            if safe is not None:
                result[key] = safe

        return result

    # ------------------------------------------------------------------
    # Empty request
    # ------------------------------------------------------------------

    def _empty_query_plan(
        self,
        context: Dict[str, Any],
    ) -> StructuredQueryPlan:
        return StructuredQueryPlan(
            intent="CLARIFICATION",
            target="user_request",
            operation="request_clarification",
            aoi={},
            time_range={},
            modalities=[],
            analysis=[],
            external_evidence_required=False,
            external_query="",
            is_follow_up=False,
            requested_measurements=[],
            confidence_threshold=None,
            uncertainty_notes=[
                "No query text was supplied."
            ],
            clarification_prompt=(
                "Please provide the question or analysis "
                "you want SatQuery-X to perform."
            ),
            clarification_options=[
                {
                    "label": "Analyze an uploaded image",
                    "value": "analyze an uploaded image",
                },
                {
                    "label": "Compare two observations",
                    "value": "compare two observations",
                },
                {
                    "label": "Find satellite imagery",
                    "value": "find satellite imagery",
                },
            ],
            input_requirements={
                "requires_user_query": True,
                "clarification_required": True,
            },
            context=self._safe_context_snapshot(
                context
            ),
            source="query_optimizer",
            optimizer_version=self.VERSION,
        )

    # ------------------------------------------------------------------
    # Explicit spatial extraction
    # ------------------------------------------------------------------

    @staticmethod
    def _extract_coordinates(
        query: str,
    ) -> Optional[List[float]]:
        """
        Extract an explicit latitude/longitude pair.

        Only reasonably unambiguous coordinate notation is accepted.
        """

        labeled = re.search(
            r"\b(?:lat(?:itude)?\s*[:=]?\s*)"
            r"(-?\d+(?:\.\d+)?)"
            r"\s*[,;/]\s*"
            r"(?:lon(?:gitude)?\s*[:=]?\s*)"
            r"(-?\d+(?:\.\d+)?)\b",
            query,
            re.IGNORECASE,
        )

        if labeled:
            lat = float(
                labeled.group(1)
            )
            lon = float(
                labeled.group(2)
            )

            if (
                -90 <= lat <= 90
                and -180 <= lon <= 180
            ):
                return [
                    lat,
                    lon,
                ]

        # Generic coordinate pair only when separated clearly.
        generic = re.search(
            r"\b(-?\d{1,3}(?:\.\d+)?)"
            r"\s*[,]\s*"
            r"(-?\d{1,3}(?:\.\d+)?)\b",
            query,
        )

        if generic:
            first = float(
                generic.group(1)
            )
            second = float(
                generic.group(2)
            )

            if (
                -90 <= first <= 90
                and -180 <= second <= 180
            ):
                return [
                    first,
                    second,
                ]

        return None

    @staticmethod
    def _extract_bbox(
        query: str,
    ) -> Optional[List[float]]:
        """
        Extract an explicitly written bbox.

        Expected order:
            west, south, east, north
        """

        match = re.search(
            r"\bbbox\s*[:=]?\s*"
            r"\[?\s*"
            r"(-?\d+(?:\.\d+)?)\s*[, ]\s*"
            r"(-?\d+(?:\.\d+)?)\s*[, ]\s*"
            r"(-?\d+(?:\.\d+)?)\s*[, ]\s*"
            r"(-?\d+(?:\.\d+)?)"
            r"\s*\]?",
            query,
            re.IGNORECASE,
        )

        if not match:
            return None

        values = [
            float(
                match.group(index)
            )
            for index in range(
                1,
                5,
            )
        ]

        west, south, east, north = values

        if not (
            -180 <= west <= 180
            and -180 <= east <= 180
            and -90 <= south <= 90
            and -90 <= north <= 90
        ):
            return None

        if west > east or south > north:
            return None

        return values

    # ------------------------------------------------------------------
    # Spatial helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _clean_spatial_dict(
        value: Mapping[str, Any],
    ) -> Dict[str, Any]:
        allowed = {
            "type",
            "name",
            "lat",
            "lon",
            "latitude",
            "longitude",
            "coordinates",
            "bbox",
            "geometry",
            "viewport",
            "crs",
            "source",
            "provider",
            "place_id",
            "display_name",
            "resolved",
            "is_resolved",
            "confidence",
        }

        result: Dict[str, Any] = {}

        for key in allowed:
            if key not in value:
                continue

            item = value[key]

            if item is None:
                continue

            if isinstance(
                item,
                (
                    str,
                    int,
                    float,
                    bool,
                    list,
                    dict,
                ),
            ):
                result[key] = _json_safe(
                    item
                )

        return result

    @staticmethod
    def _aoi_is_resolved(
        aoi: Mapping[str, Any],
    ) -> bool:
        if not aoi:
            return False

        if aoi.get(
            "resolved"
        ) is True:
            return True

        if aoi.get(
            "is_resolved"
        ) is True:
            return True

        if aoi.get(
            "geometry"
        ):
            return True

        coordinates = aoi.get(
            "coordinates"
        )

        if coordinates:
            return True

        if (
            aoi.get("lat") is not None
            and aoi.get("lon") is not None
        ):
            return True

        if aoi.get(
            "bbox"
        ):
            return True

        return False

    # ------------------------------------------------------------------
    # Image context
    # ------------------------------------------------------------------

    @staticmethod
    def _image_count(
        context: Dict[str, Any],
    ) -> int:
        """
        Count actual image inputs.

        `image_count` is accepted only as explicit context metadata.
        """

        for key in (
            "images",
            "image_assets",
            "uploaded_images",
            "assets",
        ):
            value = context.get(
                key
            )

            if isinstance(
                value,
                (list, tuple),
            ):
                return len(
                    value
                )

        value = context.get(
            "image_count"
        )

        if value is not None:
            try:
                return max(
                    0,
                    int(value),
                )
            except (
                TypeError,
                ValueError,
            ):
                pass

        return 0

    @staticmethod
    def _has_georeferencing(
        context: Dict[str, Any],
    ) -> bool:
        """
        Determine whether actual image metadata says imagery is
        georeferenced.
        """

        explicit = context.get(
            "georeferencing_available"
        )

        if explicit is True:
            return True

        images = None

        for key in (
            "images",
            "image_assets",
            "uploaded_images",
            "assets",
        ):
            value = context.get(
                key
            )

            if isinstance(
                value,
                (list, tuple),
            ):
                images = value
                break

        if not images:
            return False

        for image in images:
            if not isinstance(
                image,
                Mapping,
            ):
                continue

            if image.get(
                "is_georeferenced"
            ) is True:
                return True

            if image.get(
                "crs"
            ) and (
                image.get(
                    "transform"
                )
                or image.get(
                    "affine_transform"
                )
                or image.get(
                    "bounds"
                )
                or image.get(
                    "bounds_wgs84"
                )
            ):
                return True

        return False

    @staticmethod
    def _has_band_metadata(
        context: Dict[str, Any],
    ) -> bool:
        explicit = context.get(
            "band_metadata_available"
        )

        if explicit is True:
            return True

        images = None

        for key in (
            "images",
            "image_assets",
            "uploaded_images",
            "assets",
        ):
            value = context.get(
                key
            )

            if isinstance(
                value,
                (list, tuple),
            ):
                images = value
                break

        if not images:
            return False

        for image in images:
            if not isinstance(
                image,
                Mapping,
            ):
                continue

            for key in (
                "bands",
                "band_metadata",
                "band_names",
                "spectral_bands",
            ):
                value = image.get(
                    key
                )

                if value:
                    return True

        return False

    @staticmethod
    def _context_modalities(
        context: Dict[str, Any],
    ) -> List[str]:
        result: List[str] = []

        value = context.get(
            "modalities"
        )

        if isinstance(
            value,
            Mapping,
        ):
            for key in (
                "available",
                "requested",
                "required",
            ):
                candidate = value.get(
                    key
                )

                if isinstance(
                    candidate,
                    (list, tuple, set),
                ):
                    result.extend(
                        str(item).lower()
                        for item in candidate
                    )

        elif isinstance(
            value,
            (list, tuple, set),
        ):
            result.extend(
                str(item).lower()
                for item in value
            )

        images = None

        for key in (
            "images",
            "image_assets",
            "uploaded_images",
            "assets",
        ):
            candidate = context.get(
                key
            )

            if isinstance(
                candidate,
                (list, tuple),
            ):
                images = candidate
                break

        if images:
            for image in images:
                if not isinstance(
                    image,
                    Mapping,
                ):
                    continue

                modality = image.get(
                    "modality"
                )

                if modality:
                    result.append(
                        str(
                            modality
                        ).lower()
                    )

        normalized = []

        for value in result:
            value = value.lower().strip()

            if value in {
                "optical",
                "multispectral",
                "rgb",
                "visible",
            }:
                normalized.append(
                    "optical"
                )
            elif value in {
                "sar",
                "radar",
            }:
                normalized.append(
                    "sar"
                )
            elif value in {
                "thermal",
                "tir",
            }:
                normalized.append(
                    "thermal"
                )

        return QueryOptimizer._unique(
            normalized
        )

    @staticmethod
    def _image_temporal_context(
        context: Dict[str, Any],
    ) -> Optional[Dict[str, Any]]:
        images = None

        for key in (
            "images",
            "image_assets",
            "uploaded_images",
            "assets",
        ):
            candidate = context.get(
                key
            )

            if isinstance(
                candidate,
                (list, tuple),
            ):
                images = candidate
                break

        if not images:
            return None

        dates: List[str] = []

        for image in images:
            if not isinstance(
                image,
                Mapping,
            ):
                continue

            for key in (
                "acquisition_date",
                "acquired_at",
                "date",
                "datetime",
                "timestamp",
            ):
                value = image.get(
                    key
                )

                if not value:
                    continue

                match = re.search(
                    r"\b(20\d{2}-\d{2}-\d{2})\b",
                    str(value),
                )

                if match:
                    dates.append(
                        match.group(1)
                    )
                    break

        dates = sorted(
            set(dates)
        )

        if len(dates) >= 2:
            return {
                "start": dates[0],
                "end": dates[-1],
                "start_date": dates[0],
                "end_date": dates[-1],
                "mode": "IMAGE_METADATA_RANGE",
                "source": "image_metadata",
                "requires_provider_resolution": False,
                "comparison_required": True,
            }

        if len(dates) == 1:
            return {
                "start": dates[0],
                "end": dates[0],
                "start_date": dates[0],
                "end_date": dates[0],
                "mode": "IMAGE_METADATA_DATE",
                "source": "image_metadata",
                "requires_provider_resolution": False,
                "comparison_required": False,
            }

        return None

    # ------------------------------------------------------------------
    # Text classifiers
    # ------------------------------------------------------------------

    @staticmethod
    def _normalize_text(
        text: str,
    ) -> str:
        return re.sub(
            r"\s+",
            " ",
            text.lower().strip(),
        )

    @staticmethod
    def _contains_any(
        text: str,
        terms: Tuple[str, ...] | List[str],
    ) -> bool:
        return any(
            term in text
            for term in terms
        )

    def _is_change_query(
        self,
        query: str,
    ) -> bool:
        return self._contains_any(
            query,
            self.CHANGE_TERMS,
        )

    def _is_vegetation_query(
        self,
        query: str,
    ) -> bool:
        return self._contains_any(
            query,
            self.VEGETATION_TERMS,
        )

    def _is_water_query(
        self,
        query: str,
    ) -> bool:
        return self._contains_any(
            query,
            self.WATER_TERMS,
        )

    def _is_urban_query(
        self,
        query: str,
    ) -> bool:
        return self._contains_any(
            query,
            self.URBAN_TERMS,
        )

    def _is_thermal_query(
        self,
        query: str,
    ) -> bool:
        return self._contains_any(
            query,
            self.THERMAL_TERMS,
        )

    def _is_sar_query(
        self,
        query: str,
    ) -> bool:
        return self._contains_any(
            query,
            self.SAR_TERMS,
        )

    def _is_grounding_query(
        self,
        query: str,
    ) -> bool:
        return self._contains_any(
            query,
            self.GROUNDING_TERMS,
        )

    def _is_latest_query(
        self,
        query: str,
    ) -> bool:
        return self._contains_any(
            query,
            self.LATEST_TERMS,
        )

    def _is_satellite_query(
        self,
        query: str,
    ) -> bool:
        return self._contains_any(
            query,
            self.SATELLITE_TERMS,
        )

    def _is_web_query(
        self,
        query: str,
    ) -> bool:
        return self._contains_any(
            query,
            self.WEB_TERMS,
        )

    def _is_text_knowledge_query(
        self,
        query: str,
    ) -> bool:
        return self._contains_any(
            query,
            self.TEXT_KNOWLEDGE_TERMS,
        )

    def _is_cross_modal_query(
        self,
        query: str,
    ) -> bool:
        has_optical = self._contains_any(
            query,
            self.OPTICAL_TERMS,
        )

        has_sar = self._contains_any(
            query,
            self.SAR_TERMS,
        )

        return (
            has_optical
            and has_sar
        )

    # ------------------------------------------------------------------
    # Outputs
    # ------------------------------------------------------------------

    def _requested_outputs(
        self,
        query: str,
        understanding: Dict[str, Any],
    ) -> List[str]:
        explicit = understanding.get(
            "requested_output"
        )

        if explicit is None:
            explicit = understanding.get(
                "requested_outputs"
            )

        result: List[str] = []

        if isinstance(
            explicit,
            str,
        ):
            result.append(
                explicit.strip()
            )

        elif isinstance(
            explicit,
            (list, tuple, set),
        ):
            result.extend(
                str(value).strip()
                for value in explicit
                if str(value).strip()
            )

        output_terms = {
            "map": "map",
            "evidence": "evidence",
            "evidence map": "evidence_map",
            "change map": "change_map",
            "polygons": "polygons",
            "bounding boxes": "bounding_boxes",
            "coordinates": "coordinates",
            "area": "area",
            "percentage": "percentage",
            "report": "report",
            "summary": "summary",
            "caption": "caption",
        }

        for phrase, output in output_terms.items():
            if phrase in query:
                result.append(
                    output
                )

        return self._unique(
            result
        )

    # ------------------------------------------------------------------
    # Time normalization
    # ------------------------------------------------------------------

    @staticmethod
    def _normalize_time_range(
        value: Mapping[str, Any],
        source: str,
    ) -> Dict[str, Any]:
        result = dict(
            value
        )

        if not result:
            return {}

        result.setdefault(
            "source",
            source,
        )

        if (
            "start"
            not in result
            and "start_date"
            in result
        ):
            result["start"] = result[
                "start_date"
            ]

        if (
            "end"
            not in result
            and "end_date"
            in result
        ):
            result["end"] = result[
                "end_date"
            ]

        if (
            result.get("start")
            and result.get("end")
            and str(
                result["start"]
            )
            > str(
                result["end"]
            )
        ):
            result[
                "start"
            ], result[
                "end"
            ] = (
                result["end"],
                result["start"],
            )

        return _json_safe(
            result
        )

    # ------------------------------------------------------------------
    # Modalities
    # ------------------------------------------------------------------

    @staticmethod
    def _normalize_modalities(
        values: Any,
    ) -> List[str]:
        result: List[str] = []

        if isinstance(
            values,
            str,
        ):
            values = [
                values
            ]

        for value in values or []:
            normalized = str(
                value
            ).strip().lower()

            if normalized in {
                "optical",
                "multispectral",
                "rgb",
                "visible",
            }:
                result.append(
                    "optical"
                )
            elif normalized in {
                "sar",
                "radar",
            }:
                result.append(
                    "sar"
                )
            elif normalized in {
                "thermal",
                "tir",
            }:
                result.append(
                    "thermal"
                )

        return QueryOptimizer._unique(
            result
        )

    # ------------------------------------------------------------------
    # Confidence configuration
    # ------------------------------------------------------------------

    @staticmethod
    def _configured_confidence_threshold(
        context: Dict[str, Any],
    ) -> Optional[float]:
        """
        Return only an explicitly configured planning threshold.

        No default is created.
        """

        value = context.get(
            "confidence_threshold"
        )

        if value is None:
            return None

        try:
            number = float(
                value
            )
        except (
            TypeError,
            ValueError,
        ):
            return None

        if 0.0 <= number <= 1.0:
            return number

        return None

    # ------------------------------------------------------------------
    # Generic helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _unique(
        values: List[Any],
    ) -> List[str]:
        seen = set()
        result: List[str] = []

        for value in values:
            clean = str(
                value
            ).strip()

            if not clean:
                continue

            if clean not in seen:
                seen.add(
                    clean
                )
                result.append(
                    clean
                )

        return result

    @staticmethod
    def _as_dict(
        value: Any,
    ) -> Dict[str, Any]:
        if value is None:
            return {}

        if isinstance(
            value,
            Mapping,
        ):
            return dict(
                value
            )

        if hasattr(
            value,
            "to_dict",
        ):
            try:
                result = value.to_dict()

                if isinstance(
                    result,
                    Mapping,
                ):
                    return dict(
                        result
                    )
            except Exception:
                pass

        # Dataclass compatibility.
        try:
            from dataclasses import asdict

            result = asdict(
                value
            )

            if isinstance(
                result,
                Mapping,
            ):
                return dict(
                    result
                )
        except Exception:
            pass

        result: Dict[str, Any] = {}

        for field_name in (
            "intent",
            "target",
            "operation",
            "temporal",
            "cross_modal",
            "spatial_filter",
            "requested_output",
            "requested_outputs",
            "requested_measurements",
            "raw_text",
            "is_follow_up",
            "location",
            "time_range",
            "clarification_required",
            "clarification_prompt",
            "clarification_options",
            "geo_intent",
            "missing_data",
            "auto_search_required",
            "multi_locations",
            "context_source",
            "modalities",
            "subject",
            "entities",
            "comparison_mode",
            "external_evidence_required",
            "external_query",
        ):
            if hasattr(
                value,
                field_name,
            ):
                result[field_name] = getattr(
                    value,
                    field_name,
                )

        return result


# ============================================================================
# Module-level compatibility API
# ============================================================================


def optimize_query(
    text: str,
    session_context: Optional[Dict[str, Any]] = None,
    understanding: Any = None,
) -> StructuredQueryPlan:
    """
    Backward-compatible module-level optimizer API.
    """

    return QueryOptimizer().optimize(
        text=text,
        session_context=session_context,
        understanding=understanding,
    )


def build_structured_plan(
    text: str,
    session_context: Optional[Dict[str, Any]] = None,
    understanding: Any = None,
) -> StructuredQueryPlan:
    """
    Backward-compatible alias for optimize_query().
    """

    return QueryOptimizer().optimize(
        text=text,
        session_context=session_context,
        understanding=understanding,
    )


def json_safe(
    value: Any,
) -> Any:
    """
    Public JSON-safety helper retained for compatibility with other
    agent modules.
    """

    return _json_safe(
        value
    )


# ============================================================================
# JSON safety
# ============================================================================


def _json_safe(
    value: Any,
) -> Any:
    if value is None:
        return None

    if isinstance(
        value,
        (
            str,
            int,
            float,
            bool,
        ),
    ):
        return value

    if isinstance(
        value,
        Mapping,
    ):
        return {
            str(key): _json_safe(
                item
            )
            for key, item in value.items()
        }

    if isinstance(
        value,
        (
            list,
            tuple,
            set,
        ),
    ):
        return [
            _json_safe(
                item
            )
            for item in value
        ]

    try:
        from datetime import date, datetime

        if isinstance(
            value,
            (
                date,
                datetime,
            ),
        ):
            return value.isoformat()
    except Exception:
        pass

    try:
        from uuid import UUID

        if isinstance(
            value,
            UUID,
        ):
            return str(value)
    except Exception:
        pass

    try:
        import numpy as np

        if isinstance(
            value,
            np.ndarray,
        ):
            return value.tolist()

        if isinstance(
            value,
            np.generic,
        ):
            return value.item()
    except Exception:
        pass

    object_id = getattr(
        value,
        "id",
        None,
    )

    if object_id is not None:
        try:
            return str(
                object_id
            )
        except Exception:
            pass

    return str(
        value
    )


# ============================================================================
# Public exports
# ============================================================================


__all__ = [
    "StructuredQueryPlan",
    "QueryOptimizer",
    "optimize_query",
    "build_structured_plan",
    "json_safe",
]